### PR TITLE
Mini performance enhancement for function val()

### PR DESCRIPTION
**Pull request by R-J**
When an array is tested for a non existing $key, the current behavior also checked if the array is an object before the default value was returned. Nesting the first if clause brings a performance enhancement. Not too big and only in one special case, but nevertheless!

I've used this script to test:

~~~
<?php
define('ITERATIONS', 3000000);

ini_set('display_errors', 1);
ini_set('track_errors', 1);

function val($key, $collection, $default = false) {
    if (is_array($collection) && array_key_exists($key, $collection)) {
        return $collection[$key];
    } elseif (is_object($collection) && property_exists($collection, $key)) {
        return $collection->$key;
    }
    return $default;
}

function value ($key, $collection, $default = false) {
    if (is_array($collection)) {
        if (array_key_exists($key, $collection)) {
            return $collection[$key];
        } else {
            return $default;
        }
    } elseif (is_object($collection) && property_exists($collection, $key)) {
        return $collection->$key;
    }
    return $default;
}

$json = '{"Discussion":{"DiscussionID":29415,"Type":null,"ForeignID":null,"CategoryID":36,"InsertUserID":58653,"UpdateUserID":58653,"FirstCommentID":null,"LastCommentID":null,"Name":"Award Badges afterward","Body":"Hi,\r\n\r\nmy board is growing and now I want to award some users with a Badge.\r\nIs there a possibility to award the Badge automatically to the users which meet the requirements?","Format":"Markdown","Tags":[],"CountComments":0,"CountBookmarks":null,"CountViews":7,"Closed":0,"Announce":0,"Sink":0,"DateInserted":"2015-02-26 10:32:11","DateUpdated":"2015-02-26 10:33:08","DateLastComment":"2015-02-26 10:32:11","LastCommentUserID":null,"Score":null,"RegardingID":null,"AddonID":1178,"State":null,"LastIP":null,"QnA":null,"DateAccepted":null,"DateOfAnswer":null,"Likes":0,"Spam":0,"Abuse":0,"Source":null,"SourceID":null,"NoIndex":0,"DateLastViewed":"2015-02-26 11:27:24","Dismissed":0,"Bookmarked":0,"CountCommentWatch":0,"Participated":0,"LastDate":"2015-02-26 10:32:11","LastUserID":58653,"LastName":null,"LastPhoto":null,"InsertName":"sadgmbh","InsertPhoto":"\/\/w2.vanillicon.com\/v2\/22eb31f07194932648cd283f4eadc4f2.svg","Url":"http:\/\/vanillaforums.org\/discussion\/29415\/award-badges-afterward","Category":"Vanilla 2.1 Help","CategoryUrlCode":"vanilla-2-1","PermissionCategoryID":-1,"FirstUserID":58653,"FirstDate":"2015-02-26 10:32:11","CountUnreadComments":0,"Read":true,"UserTags":[],"XTags":[]},"CategoryID":36,"Category":{"CategoryID":36,"ParentCategoryID":-1,"CountDiscussions":1476,"AllowDiscussions":1,"Archived":0,"Archive":0,"Name":"Vanilla 2.1 Help","Description":"","Sort":18,"CssClass":"Category-vanilla-2-1","Photo":null,"PermissionCategoryID":-1,"PointsCategoryID":0,"HideAllDiscussions":0,"DisplayAs":"Discussions","InsertUserID":10878,"UpdateUserID":10878,"DateInserted":"2014-07-27 16:18:46","DateUpdated":"2014-07-27 16:35:02","UrlCode":"vanilla-2-1","TreeLeft":18,"TreeRight":19,"Depth":1,"CountComments":11428,"DateMarkedRead":null,"LastCommentID":226092,"LastDiscussionID":29412,"LastDateInserted":"2015-02-26 10:33:20","AllowedDiscussionTypes":["Discussion","Question"],"DefaultDiscussionType":null,"AllowFileUploads":1,"Type":null,"DateLastComment":"2015-02-26 10:33:20","CountAllDiscussions":1476,"CountAllComments":11428,"Url":"\/\/vanillaforums.org\/categories\/vanilla-2-1","ChildIDs":[],"PhotoUrl":"","LastTitle":"add text between breadcrumbs and topic list","LastUserID":44046,"LastDiscussionUserID":50003,"LastUrl":"\/\/vanillaforums.org\/discussion\/29412\/add-text-between-breadcrumbs-and-topic-list#latest","Unfollow":false,"Following":true,"Read":false,"PermsDiscussionsView":true,"PermsDiscussionsAdd":true,"PermsDiscussionsEdit":false,"PermsCommentsAdd":true},"Comments":[],"Page":1}';

$testObject = json_decode($json);
$testArray = json_decode($json, true);


// init vars
$CategoryID = 0;
$time_start = microtime(true);
$time_end = microtime(true);
$time = $time_end - $time_start;

for ($i = 0; $i < 3; $i++) {


// function val, get non existing from array
$time_start = microtime(true);
for ($k = 0; $k < ITERATIONS; $k++) {
    $Quark = val('Quark', $testArray, 'Quatsch');
    // $CategoryID = val('CategoryID', $testArray);
    
}
$time_end = microtime(true);
$time = $time_end - $time_start;
echo "$time seconds for val/array<br>\n";

// function value, get non existing from array
$time_start = microtime(true);
for ($k = 0; $k < ITERATIONS; $k++) {
    $Quark = value('Quark', $testArray, 'Quatsch');
    // $CategoryID = value('CategoryID', $testArray);
}
$time_end = microtime(true);
$time = $time_end - $time_start;
echo "$time seconds for value/array<br>\n";

echo "<br />\n";

}
~~~

### CODE REVIEW

**Comment by R-J** [comment]
Please give feedback if you like to see a PR for GetValue, too

**Comment by tburry** [comment]
Very cool stuff. Do you have the output of your test script?

**Comment by R-J** [comment]
I've let it run two times for you and here are the results:

~~~
23.45894408226 seconds for val/array<br>
17.992506980896 seconds for value/array<br>
<br />
22.801592111588 seconds for val/array<br>
18.346288204193 seconds for value/array<br>
<br />
23.808209180832 seconds for val/array<br>
18.708534002304 seconds for value/array<br>
<br />
21.437798976898 seconds for val/array<br>
16.611474990845 seconds for value/array<br>
<br />
22.061836957932 seconds for val/array<br>
17.530173063278 seconds for value/array<br>
<br />
23.121591091156 seconds for val/array<br>
16.89543390274 seconds for value/array<br>
<br />
~~~

Excel tells me the average is 22.8:17.7 which would make it 20-30% faster (but only for non existing array keys!)

Don't ask me for the specs of that root server I'm using...

**Comment by hgtonight** [comment]
On my local host I am getting 29-34% faster.

**Comment by R-J** [comment]
With existing array keys I get:
~~~
old val:  18,29219747
new val: 17,95019746
= 1,019052716
~~~

and for objects 

~~~
old val: 24,47819928
new val: 24,27358131
= 1,008429658
~~~

I'd say it has no effect on objects and maybe a very tiny positive effect on existing array keys, but that could be just an error in measurement. But there is no negative effect

**Comment by hgtonight** [comment]
The proposed function is -0.40130723405848% slower for existing keys in an array
The proposed function is 0.10038844808415% faster for existing members in an object
The proposed function is 32.010780703594% faster for keys not in an array
The proposed function is -0.17894859673027% slower for members not found in an object

With:

~~~
<?php

define('ITERATIONS', 1000000);

ini_set('display_errors', 1);
ini_set('track_errors', 1);

function val($key, $collection, $default = false) {
    if (is_array($collection) && array_key_exists($key, $collection)) {
        return $collection[$key];
    } elseif (is_object($collection) && property_exists($collection, $key)) {
        return $collection->$key;
    }
    return $default;
}

function value($key, $collection, $default = false) {
    if (is_array($collection)) {
        if (array_key_exists($key, $collection)) {
            return $collection[$key];
        } else {
            return $default;
        }
    } elseif (is_object($collection) && property_exists($collection, $key)) {
        return $collection->$key;
    }
    return $default;
}

$json = '{"DiscussionID":29415,"Type":null,"ForeignID":null,"CategoryID":36,"InsertUserID":58653,"UpdateUserID":58653,"FirstCommentID":226098,"LastCommentID":226112,"Name":"Award Badges afterward","Body":"Hi,\r\n\r\nmy board is growing and now I want to award some users with a Badge.\r\nIs there a possibility to award the Badge automatically to the users which meet the requirements?","Format":"Markdown","Tags":[],"CountComments":3,"CountBookmarks":null,"CountViews":23,"Closed":0,"Announce":0,"Sink":0,"DateInserted":"2015-02-26 10:32:11","DateUpdated":"2015-02-26 10:33:08","InsertIPAddress":"213.179.147.226","UpdateIPAddress":"213.179.147.226","DateLastComment":"2015-02-26 20:08:32","LastCommentUserID":38268,"Score":null,"RegardingID":null,"AddonID":1178,"State":null,"LastIP":null,"QnA":null,"DateAccepted":null,"DateOfAnswer":null,"Likes":0,"Spam":0,"Abuse":0,"Source":null,"SourceID":null,"NoIndex":0,"DateLastViewed":"2015-02-26 20:08:32","Dismissed":0,"Bookmarked":0,"CountCommentWatch":3,"Participated":1,"LastDate":"2015-02-26 20:08:32","LastUserID":38268,"LastName":"hgtonight","LastEmail":"hgtonight@daklutz.com","LastPhoto":"http:\/\/cd8ba0b44a15c10065fd-24461f391e20b7336331d5789078af53.r23.cf1.rackcdn.com\/www.vanillaforums.org\/userpics\/205\/nQM3WWQ1NUY1C.png","InsertName":"sadgmbh","InsertEmail":"martin.molle@s-a-d.de","InsertPhoto":"\/\/w2.vanillicon.com\/v2\/22eb31f07194932648cd283f4eadc4f2.svg","Url":"http:\/\/vanillaforums.org\/discussion\/29415\/award-badges-afterward","Category":"Vanilla 2.1 Help","CategoryUrlCode":"vanilla-2-1","PermissionCategoryID":-1,"FirstUserID":58653,"FirstDate":"2015-02-26 10:32:11","CountUnreadComments":0,"Read":true,"UserTags":[],"XTags":[]}';

$testObject = json_decode($json);
$testArray = json_decode($json, true);

compare_val_value($testArray, 'Format', 'Default', 'existing keys in an array');
compare_val_value($testObject, 'Format', 'Default', 'existing members in an object');
compare_val_value($testArray, 'Quark', 'Quatsch', 'keys not in an array');
compare_val_value($testObject, 'Quark', 'Quatsch', 'members not found in an object');

function compare_val_value($collection, $key, $default, $context) {
    $time_start = microtime(true);
    for ($k = 0; $k < ITERATIONS; $k++) {
        $Quark = val($key, $collection, $default);
    }
    $time_end = microtime(true);
    $time_old = $time_end - $time_start;

    $time_start = microtime(true);
    for ($k = 0; $k < ITERATIONS; $k++) {
        $Quark = value($key, $collection, $default);
    }
    $time_end = microtime(true);
    $time_new = $time_end - $time_start;

    if ($time_old > $time_new) {
        $percent_speed_up = (($time_old / $time_new) - 1) * 100;
        echo "The proposed function is ${percent_speed_up}% faster for ${context}<br>\n";
    } else {
        $percent_slow_down = (($time_old / $time_new) - 1) * 100;
        echo "The proposed function is ${percent_slow_down}% slower for ${context}<br>\n";
    }
}
~~~

**Comment by hgtonight** [comment]
Like @R-J said, the other uses cases are probably just noise, but I still like looking at numbers.

**Comment by R-J** [comment]
Since the way objects are handled isn't changed at all in the function, it is not possible that it will perform better in one case and worse in the other when only testing with objects => noise
q.e.d ;-)

**Comment by tburry** [comment]
Awesome stuff guys!

**Pull request merged**
