### PR TITLE
Avoid including root category in /categories/apiv1list

### PR DESCRIPTION
**Pull request by initvector**
The root category is included in the /categories/apiv1list endpoint.

This update checks for the existence of the root category before the data is delivered and purges it if present.

### CODE REVIEW

**Comment by linc** [comment]
Are we pretty confident no one is depending on this behavior?

**Comment by JulieVanilla** [comment]
I know that this was flagged by Harvard a couple of months ago, as this was a new change then.

**Comment by linc** [comment]
You're saying this is *reverting* the unexpected change, and they'll be OK with that?

**Comment by JulieVanilla** [comment]
They are annoyed by the root category showing up, so yes, they would be okay with that.

**Pull request merged**
