### PR TITLE
Add quote formatting to discussions + updating old code

### PR DESCRIPTION
**Pull request by R-J**
Changes:
1. Added if brackets where necessary
2. Replaced **variable** RenderQuotes $with $HandleRenderQuotes
3. Make Settings Title translatable
4. Eliminate one superfluous if else block
5. Stripped out unneeded variable
6. Replaced use of deprecated `$Sender->EventArguments['Object']`
7. Added support for quotes in discussions
8. Stripped unneeded config settings from Setup and OnDisable

*Phew...* this is the longest pull request I've ever submitted! So I'm quite nervous and that's why I explain here what I have done in detail

Explanations:
2.) Added variable $HandleRenderQuotes because there was an ambiguous use of a variable and a function called `RenderQuotes`: `$this->RenderQuotes = C('Plugins.Quotes.RenderQuotes', TRUE);`
3.) `$Sender->Title("Quotes Settings");` to `$Sender->Title(T("Quotes Settings"));`
4.) I've changed this:
~~~
      $UserID = $ViewingUserID = Gdn::Session()->UserID;

      if ($Sender->User->UserID != $ViewingUserID) {
         $Sender->Permission('Garden.Users.Edit');
         $UserID = $Sender->User->UserID;
      }

      $Sender->SetData('ForceEditing', ($UserID == Gdn::Session()->UserID) ? FALSE : $Sender->User->Name);
~~~
to that
~~~
      $UserID = Gdn::Session()->UserID;
      $ViewingUserID = $UserID;

      if ($Sender->User->UserID != $ViewingUserID) {
         $Sender->Permission('Garden.Users.Edit');
         $UserID = $Sender->User->UserID;
      }

      if ($UserID == Gdn::Session()->UserID) {
         $Sender->SetData('ForceEditing', FALSE);
      } else {
         $Sender->SetData('ForceEditing', $Sender->User->Name);
      }
~~~
and then I've seen that I start with `$UserID = Gdn::Session()->UserID;` and in the second if clause it is checked if that is still the case. It could only change if the first if clause is true and that's why I squashed it to
~~~
      $UserID = Gdn::Session()->UserID;
      $ViewingUserID = $UserID;

      if ($Sender->User->UserID != $ViewingUserID) {
         $Sender->Permission('Garden.Users.Edit');
         $UserID = $Sender->User->UserID;
         // taken from the second "else"
         $Sender->SetData('ForceEditing', $Sender->User->Name);
      } else {
         // from the second if, because $UserID has changed
         $Sender->SetData('ForceEditing',  FALSE);
      }
~~~

5.) There have been a relict from something else in there (`$Reply = T('Reply'); // help capture translation.`) which could be deleted safely

6.) I've replaced several references to `$Sender->EventArguments['Object']` with $Object which I've declared with
~~~
      if (isset($Sender->EventArguments['Comment'])) {
         $Object = $Sender->EventArguments['Comment'];
      } elseif (isset($Sender->EventArguments['Discussion'])) {
         $Object = $Sender->EventArguments['Discussion'];
      } else {
         return;
      }
~~~

7.) When `$Sender->EventArguments['Object']` has been state of the art, "BeforeCommentDisplay" has also been fired for discussions. That is no more and that's why I added
~~~
   public function DiscussionController_BeforeDiscussionDisplay_Handler($Sender) {
      $this->RenderQuotes($Sender);
   }

   public function PostController_BeforeDiscussionDisplay_Handler($Sender) {
      $this->RenderQuotes($Sender);
   }
~~~

8.) Setup() sets a config setting which is resetted by OnDisable() but it is not needed anywhere (the same as https://github.com/vanilla/vanilla/pull/2556)

1.) "*Hail to Lord Brackos!*"  ;-)

### CODE REVIEW

**Comment by linc** [comment]
I think your other Quotes PR created a merge conflict in this one.

**Comment by R-J** [comment]
Oh sh... That was the most complex PR I've ever made and it failed :-(

So what's the procedure? I guess I have to close this PR and change the current master branch, correct?

**Comment by linc** [comment]
Nope! Just pull master branch to this branch, fix the conflicts, and push it here :)

**Comment by R-J** [comment]
OMG! It is unbelievable how hard it is to find out how to do this when you try to search the internet for "handle merge conflicts" or anything like that. Either "simply pull into your repo!" or "GitHub for absolute beginners".

Here's what I've done (for my own future reference...)
git clone https://github.com/R-J/vanilla.git
git checkout patch-49
git pull https://github.com/vanilla/vanilla.git
git add plugins/Quotes/class.quotes.plugin.php
git commit -m 'Fix merge conflicts'
git push https://github.com/R-J/vanilla.git patch-49

**Comment by linc** [comment]
@R-J You didn't fix some of the conflicts.

screen shot 2015-03-23 at 9 40 49 am

**Comment by R-J** [comment]
Sorry, I'm out. It took me longer to make this false correction than it took me to change the plugin. Either anyone helps me out or I'll close this PR and create a new one.

If only working with git could be at least half as easy as writing code for Vanilla...

**Comment by linc** [comment]
The only step you missed was before "git add x" you need to edit the marked conflicts in the code (as seen above). The subsequent `add` and `commit` tell git that you've manually fixed the conflict.

In this case, just make 1 more commit on the branch that changes those lines to what they should be. (In both instances, the 5 lines of code should be truncated to just the 1-line comment).

**Comment by hgtonight** [comment]
Here is what I did:

    git remote add r_j_fork https://github.com/R-J/vanilla.git
    git fetch r_j_fork patch-49
    git checkout 4867d078e1a4471b20fcb0cbdc30de9e4dd9117d
    git checkout -b hotfix/quote-formatting
    git pull upstream master

Now I fix the merge conflicts by opening the conflicted files (`git status` will list the files in conflict). Now that they are done:

    git add plugins/Quotes/class.quotes.plugin.php
    git commit
    git push origin hotfix/quote-formatting

Now I am done, just need to file a PR.

**Comment by R-J** [comment]
Thanks guys. A girl I know is quite a good coder. I promise I make her explain me git the next time we meet.

**Pull request merged**
