### PR TITLE
Create option to use KB header in boilerplate

### PR DESCRIPTION
**Pull request by slafleche**
This PR updates the boiler-plate theme to fix several issues. Most notably, adding a site option to use the KB's header on the forum side.

- Turn on KB's header by setting `$Configuration['Feature']['DataDrivenTitleBar']['Enabled'] = true;`
    - Added "TitleBarHamburger" component. This component is only meant to be used on the forum side until we merge the two designs.
    - Fixed some style conflicts between KB header and boilerplate
    - Update boiler-plate's default.master view to conditionally include one header or another as well as pass the hamburger's contents to both. 
- Increased max width of images to 100%
- Set max-width on legacy video embeds
- Fixed overflow problem in dashboard's modal
- Match KB's width

For: https://github.com/vanilla/vanilla/issues/9614
For: https://github.com/vanilla/support/issues/333
For: https://github.com/vanilla/support/issues/830

Companion PR: https://github.com/vanilla/knowledge/pull/1397
Companion PR: https://github.com/vanilla/multisite/pull/314#pullrequestreview-323203622

** Note that this PR does not yet include changes to Keystone. I have a meeting with Isis on Monday to discuss this. **

### CODE REVIEW

**Comment by charrondev** [comment]
A few visual notes:

## Mobile MeBox

image

- Button styles are missing some reset (check our reset mixin).
- Don't know what that dot is.

## Dropdown menu

image

- Missing subcommunity dropdown.
- Add button is clipped

**Comment by slafleche** [comment]
I simplified the hamburger contents to match what we have in the menu. I also hid the search boxes when we have the KB header. 

Also fixed some styling issues in mebox.

**Comment by charrondev** [comment]
So issues still remaining

- The logo disappears on hover.
- The tab buttons in the MeBox are styled incorrectly.
- The subcommunity button isn't appearing (fix for desktop [here](https://github.com/vanilla/multisite/pull/314), we'll have to talk about mobile in person).
- The mobile nav modal is missing padding at the top for some reason

**Comment by igraziatto** [comment]
@irina-vanillaforums @alexbrohman be aware that of those changes being added to the boilerplate. Come and see me if you have any questions.

**Comment by charrondev** [comment]
@slafleche We should use the same font weight in modals between keystone and KB (goes for the normal nav menu as well).

**Comment by slafleche** [comment]
Screen Shot 2019-11-27 at 09 55 22

**Pull request merged**
