### PR TITLE
Add Locale Based "language" to HTML and Newsfeed Templates

### PR DESCRIPTION
**Pull request by R-J**
Add "lang" attribute to templates and used Vanillas locale for the value.

### CODE REVIEW

**Comment by linc** [comment]
Looks good but pinging @tburry since he's Locales Man.

**Comment by linc** [comment]
@R-J wanna give me write access to your fork?

**Comment by R-J** [comment]
I made you a collaborator (hope that it is what is needed to give you access)

**Comment by tburry** [comment]
I rebased this PR off of master to fix the merge conflicts. I don't know why the diff doesn't show that, but I think everything is good. Please let me know if I goofed.

**Comment by R-J** [comment]
Sorry, I understand English quite well, but when it comes to githubish, I suck... :-/

Do you need me to change anything?

**Pull request closed without merging**
