### PR TITLE
adding soundcloud

### PR DESCRIPTION
**Pull request by adrianspeyer**
All member needs to do is post share url and soundcloud track will be embeded.

### CODE REVIEW

**Comment by linc** [comment]
See https://github.com/vanilla/vanilla/pull/2725 ; otherwise looks good

**Comment by adrianspeyer** [comment]
Made the change as requested +1

**Comment by adrianspeyer** [comment]
Added it back. I was too eager in making it less.

**Comment by linc** [comment]
Just noticed this is against stage. :P We're not really using that branch unless it's a big change we wanna do more testing on.

**Pull request closed without merging**
