### PR TITLE
Fix spam count not displaying in memodule

### PR DESCRIPTION
**Pull request by dannimajdalani**
closes https://github.com/vanilla/support/issues/1785

### To Test

- Report a post as spam
- check the count.

### CODE REVIEW

**Comment by SaadTawfiq** [comment]
@blutarch Hi Richard, this is still an issue for Versus Arthritis. We tested it this morning and the spam queue still doesn't show a number.

**Comment by dannimajdalani** [comment]
@SaadTawfiq this ticket is assigned to me.
Screen Shot 2020-04-29 at 9 40 20 AM

Screen Shot 2020-04-29 at 9 37 43 AM

As always, It would need to be deployed to the client's cluster before you see that change taking effect.
It has only been merged 2 days ago.

**Comment by SaadTawfiq** [comment]
@dannimajdalani 
Sorry about that. Do you know when this will be pushed?

**Comment by dannimajdalani** [comment]
> @dannimajdalani
> Sorry about that. Do you know when this will be pushed?

Release notes are usually a good place to find out what will be deployed to clusters. You can also look at the calendar to check when a specific release will be deployed. 

**Example**
This PR has been merged 2 days ago
On the calendar, 2020.008 (current release) has been branched on the 16th, so this PR did not make it to the current release. (2020.008 release notes do not mention this PR)
2020.009 will have this fix. On the calendar this will be deployed May 11.

**Comment by SaadTawfiq** [comment]
@dannimajdalani  Thank you Dani, will look at the release notes from now on! :)

**Comment by linc** [comment]
This wasn't a bug. It was purposefully removed in 2013 and maked not a bug in 2017: https://github.com/vanilla/vanilla/issues/5693

The spam queue isn't a thing to "manage" like it's a to do list (it's expressly designed to be ignored) but you've now made it into one, so many sites are going to have thousands of alerts in their Dashboard, obscuring actual items like Applicants and Moderator approvals. 

Personally, I have 53,000 items in an alert bubble on one of my sites. Not super cool.

**Comment by dannimajdalani** [comment]
@linc that makes sense. We will revert it and just keep the count next to the spam link.

**Pull request merged**
