### PR TITLE
Allow disabling commenting ajax so that page will refresh on submission

### PR DESCRIPTION
**Pull request by nervoustwit**
In order to test, add 
$Configuration['Vanilla']['Discussion']['DisableAjax'] = true; 
to config.

### CODE REVIEW

**Comment by mtschirs** [comment]
All relevant page content should already refresh on submission of a new comment... see vanilla/js/discussion.js in line 182: // If adding a new comment, show all new comments since the page last loaded, including the new one.

**Comment by linc** [comment]
@mtschirs I don't believe that comment reflects current functionality. We no longer return partial comment payloads because it causes irregular comment queries which effects performance.

**Comment by tburry** [comment]
I'm really not in favor of this as a core change. Sounds like a better place for a theme hack to me. What's the reasoning behind this?

**Comment by linc** [comment]
It's a common problem on very busy forums to end up having an out-of-sequence comment you just made on the page. Since it's a widespread issue, it seemed more useful as a core modification so we can apply it to other sites having the same issue rather than hacking all their themes.

**Comment by linc** [comment]
I'm not against doing it as a theme hack if you really wanna do it that way, but I think it's time to admit our standard behavior here doesn't scale very well.

**Comment by tburry** [comment]
Here is what I'd prefer:

1. Look into how to remove the event handler on the comment form.
2. Create a js recipe that can be done in a theme or pocket.
3. Hack into sites that want it.

**Comment by bleistivt** [comment]
$('.CommentButton').on('click', function (e) {
        e.stopPropagation();
    });

**Pull request closed without merging**
