### PR TITLE
Remove ad-hoc array function calling from GDN_SQL.

### PR DESCRIPTION
**Pull request by tburry**
This is just grabbing the changes from https://github.com/vanilla/vanilla/pull/2355 into master.

### CODE REVIEW

**Comment by brandonprry** [comment]
I don't believe this made it into the 2.1.7 release. Is this slated for 2.1.8?

**Comment by tburry** [comment]
Hey @linc, any thoughts on whether this is in 2.1.7?

**Comment by linc** [comment]
It did not. This and the Attributes fix need to go to 2.1 branch for 2.1.8, and there is another unrelated patch I'm waiting on to release that. The SQL fix in 2.1.7 is this one: https://github.com/vanilla/vanilla/pull/2272

**Comment by linc** [comment]
This was released in 2.1.8, fyi.

**Pull request merged**
