### PR TITLE
Update htmLawed to use vanilla/htmlawed

### PR DESCRIPTION
**Pull request by initvector**
This update primarily focuses on moving the htmLawed library used from one bundled with Vanilla to instead use a copy of [vanilla/htmlawed](https://github.com/vanilla/htmlawed) as a Composer requirement.

In addition, the plug-in has undergone revisions to remove unused code, update naming conventions and general refactoring.

### CODE REVIEW

**Comment by initvector** [comment]
I've used the following markup for some basic tests.

```html
<p class="AlignCenter">Align Center</p>
<p class="InvalidClass">Invalid Class</p>
<script>alert('Hello world.');</script>
<p><a href="http://www.google.com">Google</a></p>
```

The result should be:
1. "Align Center" should retain the `AlignCenter` class and be horizontally centered.
2. "Invalid Class" should have `InvalidClass` stripped from its class attribute.
3. The `script` tags surrounding the alert code should be removed.
4. A `rel="nofollow"` should be added to the Google link.

**Comment by linc** [comment]
Be sure to talk to me before this merges.

**Comment by linc** [comment]
Conflicts because we updated the library

**Comment by initvector** [comment]
Branch has been rebased.

**Comment by initvector** [comment]
Travis CI build fails for PHP 7 with the following:

```
0.02s$ phpenv global 7.0
rbenv: version `7.0' not installed
The command "phpenv global 7.0" failed and exited with 1 during .
Your build has been stopped.
```

**Pull request merged**
