### PR TITLE
Let All Categories Show "Read" Information Correctly

### PR DESCRIPTION
**Pull request by R-J**
Fix https://github.com/vanilla/vanilla/issues/6856

Check was only done when DateMarkedRead was set manually before. This would lead to false negatives for every category which was never been marked read.
Also changed the LookBackCount being used as the limit for the get operation. The hard coded value leads to false results for forums with more than 50 discussion per page.

### CODE REVIEW

**Comment by charrondev** [comment]
@R-J Are you going to fix the conflicts on this one soon?

**Comment by charrondev** [comment]
Have you tried rebasing instead of merging? That might go more smoothly.

**Comment by charrondev** [comment]
I'm sorry @R-J I've really tried to merge/rebase this for you, but it's just not happening. https://github.com/vanilla/vanilla/pull/6855 pretty much 100% changed this function and this was not based on that. This PR will need to be tried again from master.

Recreating an ~10 line change (excluding whitespace) will be a lot easier than trying to merge these  together.

**Comment by R-J** [comment]
@charrondev At the end it has even been just 5 lines :-D

**Pull request closed without merging**
