### PR TITLE
Fix user availability search not working on connect registration

### PR DESCRIPTION
**Pull request by dannimajdalani**
closes https://github.com/vanilla/support/issues/726
related https://github.com/vanilla/vanilla-patches/pull/592
### Details

When trying to connect over SSO with (Private-communities & Registration not set to basic) users cannot connect.
When inspecting the page, you'll notice this error:

Screen Shot 2019-08-20 at 11 43 39 AM

We added this definition https://github.com/vanilla/vanilla/blob/46c27769344e83dd6752cc5bb2b76c765dae3357/applications/dashboard/controllers/class.entrycontroller.php#L79

https://github.com/vanilla/vanilla/blob/c120a36c1f901726f473f3f5bf27e72c1d2b641f/applications/dashboard/js/entry.js#L3

that's supposed to be turning off availability searches if the feature isn't available, but it isn't

 
### What Changed
In this PR we check if userSearchAvialable is true before we call checkConnectName();
 
Those availability checks are also updated to use "data" requests (e.g. /user/usernameavailable.json?name=f), instead of "regular" requests (e.g. /user/usernameavailable/f). When these requests fail, Its expect the exception message in the info popup.

### To Test

- Make sure you are not in a private community. Try using the /user/emailavailable and /user/usernameavailable endpoints while not signed in. Verify they function as expected.
- Enable private community and set your site's registration method to basic, if it isn't already.
- Try using /user/emailavailable and /user/usernameavaialble again. Verify they function normally.
- Change your site's registration method to invitation (or approval).
- Try using the /user/emailavailable and /user/usernameavailable endpoints again. They should now throw exceptions.
- Try using the site's regular registration form. You should not see any network requests to either /user/emailavailable or /user/usernameavailable while filling out the form.
- Disable private community and switch back to basic registration.
- Try using the site's regular registration form again. This time, you should see requests made to /user/emailavailable and /user/usernameavailable as you move from field to field in the form. Verify errors are displayed in the form, before you submit, if the username or email address are already taken on the site.

### Test using SSO

- set your community to private and registration to connect
- Using SSO provider, try connecting to the site.
- enter a username that already exists in the db (should get name already exists if private community is disabled)
- correct it and try with a new username

### CODE REVIEW

**Comment by andrewdodson** [comment]
Ryan requested I help test this.  Everything worked for me as expected. 

**Tested**
image

**Test Using SSO (linkedin)**
image

**Comment by cchabilall83** [comment]
worked for me on 112

**Comment by thaliegordon** [comment]
Hey guys,

Looks like the client is getting a "Nonce Not Found" error when trying to login in:

1. Log out of active forum instance

2. Login to Next Door Member Area
members.nextdoorstudios.com
Username: SSOtest1
Password: 1ssotest

3. Click Forum

4. Get Nonce Not Found Error

Any insight? I can ask more questions if necessary just let me know.

pfohkcoebcgdmiam

**Comment by dannimajdalani** [comment]
I just tested with this account, it logged in without that error for me.

**Comment by thaliegordon** [comment]
Same, not sure what the problem could be - I'll ask the client to try a different browser perhaps?

Could it be a cache issue? I don't know more than I Google which points me towards an API based OAuth login failure...not sure what I can do to help but let me know.

**Pull request merged**
