### PR TITLE
Update PHPMailer and extend it to add some functionalities.

### PR DESCRIPTION
**Pull request by DaazKu**
Update PHPMailer to use composer and create a shim class that provide the custom functionalities that we added in our modified version of PHPMailer.

I've decided to completely drop the STOP_SERVER constant since it is not used in our base code anymore.
The risk of it being used externally is extremely low and keeping it would mean we would have to redefine some functions which it a really bad idea. I'm also not declaring it so that if anyone used it they will know real fast that it does not exist anymore.

Fix: https://github.com/vanilla/vanilla/issues/3895

### CODE REVIEW

**Comment by initvector** [comment]
Code looks good.  I tested several mail messages and functionality seems solid.

I'd like confirmation that it's okay to axe `STOP_SERVER`.  Carrying it over was a large part of the previous issue's thread and the conclusion there, as of June, seemed to be it should be staying.

**Comment by tburry** [comment]
We need to differentiate between:

1. An error that occurred because the email was malformed in some way. These kinds of emails cannot be resent.
2. An error that occurred because of network issues or latency. These kinds of emails can be retried.

I'm pretty sure that the STOP_SERVER was for the second category.

**Comment by DaazKu** [comment]
We are not checking for that ANYWHERE in our code but I added a function that let us do that.

**Comment by tburry** [comment]
We are checking for it, or rather the absence of STOP_CRITICAL in the activity model. The STOP_SERVER then gets put as the result status in the activity table.

**Comment by DaazKu** [comment]
Thanks for clarifying that up!

**Comment by DaazKu** [comment]
Good to go.

**Pull request merged**
