### PR TITLE
Update Dashboard news feed, add releases feed

### PR DESCRIPTION
**Pull request by linc**
* Adds a new "Updates" feed above "News" in the Dashboard that pulls from the "Releases" category on the vforg forum (latest 2).
* Simplifies how feeds are called, allows URL override and/or shutting down a feed.

Prerequisites:
https://github.com/vanilla/community/pull/22
https://github.com/vanilla/vanillainfrastructure/pull/8

### CODE REVIEW

**Comment by tburry** [comment]
The seems to only be appropriate for OSS. What is the affect on hosted?

**Comment by linc** [comment]
My other two PRs answer that. The community repo PR maintains the news feed as pointing to the vfcom blog, and the inf PR disables the 'updates' feed and hides it via vfoptions.

**Comment by tburry** [comment]
I've merged the other two PRs. I think at least the one needs to be launched before I can test this one. Let me know when it's done.

**Comment by tburry** [comment]
The vanilla stats plugin has its own view that will need the releases feed added. Currently it's not there.

**Comment by linc** [comment]
I don't follow. The feed gets ajaxed in. It has a div with class `NewsColumn` which should be all it needs.

**Comment by linc** [comment]
The other PR on community repo did get launched.

**Comment by linc** [comment]
I fixed the VanillaStats thing and also fixed its coding standards because there were some real bad ones in there.

**Pull request merged**
