### PR TITLE
Make youtube embed work for playlists.

### PR DESCRIPTION
**Pull request by John0x00**

### CODE REVIEW

**Comment by linc** [comment]
I tried this and it did not embed:

`https://www.youtube.com/playlist?list=PL65C2A00E52E2F951`

I tried this and it did not embed:

`<iframe width="560" height="315" src="//www.youtube.com/embed/videoseries?list=PL65C2A00E52E2F951" frameborder="0" allowfullscreen></iframe>`

So I'm not sure what the anticipated use case was here for enabling playlists. Those are the 2 reasonable ways I'd see for someone including a playlist in content.

**Comment by tburry** [comment]
I don't think this is to allow embedding of playlists, but to allow embedding of videos that are in a playlist. Not sure though. Maybe @beckyvb can give an example.

**Comment by bleistivt** [comment]
It would be cool if this would also cover m.youtube.com links. Mobile users are often confused why their links won't expand.

**Comment by beckyvb** [comment]
Good call, @bleistivt

**Comment by tburry** [comment]
Hey @beckyvb, can you post a variety of links you've tested with?

**Comment by beckyvb** [comment]
Yep! Here are the links I've tested with:
http://www.youtube.com/playlist?list=PL4CFF79651DB8159B
https://www.youtube.com/playlist?list=PL4CFF79651DB8159B
https://www.youtube.com/watch?v=sjm_gBpJ63k&list=PL4CFF79651DB8159B&index=1
http://youtu.be/sjm_gBpJ63k
https://www.youtube.com/watch?v=sjm_gBpJ63k
http://YOUTU.BE/sjm_gBpJ63k?list=PL4CFF79651DB8159B
http://youtu.be/GUbyhoU81sQ?t=1m8s
https://m.youtube.com/watch?v=iAEKPcz9www
https://youtube.com/watch?v=iAEKPcz9www

**Comment by linc** [comment]
I was really hoping they were all rickrolls.

**Comment by linc** [comment]
De-conflicted.

**Pull request merged**
