### PR TITLE
Mobile: Always use modern layout for discussions

### PR DESCRIPTION
**Pull request by bleistivt**
Temporarily set the default (modern) view for discussions in the themehooks.

#1666

### CODE REVIEW

**Comment by linc** [comment]
I like this change, but want @tburry to weigh in too.

**Comment by linc** [comment]
For reference, this sort of change should be made to `stage` in the future. This isn't really a hotfix, it's a noticeable feature change.

**Comment by bleistivt** [comment]
I can open this against stage right now, if you want

**Comment by linc** [comment]
Yeah, let's do that, actually. That'd make me feel better because then we'll notice if a cloud client's site were unexpectedly altered by this before it made it into production. I also think, barring Todd reviewing this sooner, I'll hang off on merging this until next week after the current batch of staged features goes off to allow more review time.

**Pull request closed without merging**
