### PR TITLE
Remove jQuery UI from all controllers

### PR DESCRIPTION
**Pull request by bleistivt**
see #3057

This replaces jQuery UIs .effect() with a shim using CSS animations and
removes the library from all controllers.

### CODE REVIEW

**Comment by kaecyra** [comment]
You're not seeing issues after making this change yourself? Testing reveals no weird console errors?

**Comment by bleistivt** [comment]
Yes, I've been running my forum for more than a month with this now.

Apart from the highlight `.effect`, everything that needs jQuery UI imports its own custom build anyway, like nestedSortable or the editors upload bar widget.

**Comment by bleistivt** [comment]
Definitely requires testing in case you might use it internally somewhere, but I believe the bandwith (and on low-end devices likely parsing speed) savings are worth it.
ss 2015-09-18 at 06 04 54

**Comment by linc** [comment]
Cleaned up the merge with #3315

**Pull request closed without merging**
