### PR TITLE
Replace ConsolidateArrayValuesByKey() with array_column().

### PR DESCRIPTION
**Pull request by tburry**
The new `array_column()` provides 99% of the functionality of `ConsolidateArrayValuesByKey()` and has the benifit of having a nicer name.

### CODE REVIEW

**Comment by hgtonight** [comment]
This does bump the version requirement of PHP to 5.5 ([`array_column()`](http://php.net/manual/en/function.array-column.php))

**Comment by tburry** [comment]
We have a compatibility version of it [here](https://github.com/vanilla/vanilla/blob/ec75dc79301c524ff4de2c619d7d95c9e2255298/library/core/functions.general.php#L97).

**Comment by hgtonight** [comment]
+1 :)

**Comment by tburry** [comment]
Also note that although this PR doesn't remove all ConsolidateArrayValuesByKey() uses I think it's good to get this merged before the code diverges.

**Pull request merged**
