### PR TITLE
Add checking for CategoryID for permissions

### PR DESCRIPTION
**Pull request by initvector**
This update alters `CategoryModel::checkPermission` to consider `CategoryID`, in addition to `PermissionCategoryID`.  It also swaps out some existing per-category permission checks to use this revised function.

### CODE REVIEW

**Comment by tburry** [comment]
I'm putting this on hold for now because we don't need it for our current use-case.

**Comment by tburry** [comment]
I pushed this off to next spring. You can do some testing then @initvector.

**Comment by linc** [comment]
@initvector Would you resolve the conflicts?

@DaazKu Wanna kick the tires on this? This is the sort of thing that generates support requests if we miss anything.

**Comment by initvector** [comment]
Conflicts: Resolved :godmode:

**Comment by DaazKu** [comment]
I can tackle this tomorrow probably!

**Pull request merged**
