### PR TITLE
The Spacening

### PR DESCRIPTION
**Pull request by tburry**
Convert indents from three to four spaces. This is part of a larger project to standardize Vanilla's code.

When looking at code diffs on this pull request I strongly recommend you use `?w=1` like [this](https://github.com/vanilla/vanilla/pull/2783/files?w=1).

### CODE REVIEW

**Comment by linc** [comment]
My IDE is ready.

**Comment by linc** [comment]
/applications/conversations/views/messages/popin.php is incorrect on line 24.

**Comment by linc** [comment]
One thing I'm noticing is that stacked variable alignment is getting undone (e.g. an array where all the arrows are horizontally aligned). This is a little annoying but acceptable collateral damage I guess.

**Comment by linc** [comment]
I guess we're doing this now with empty catches?

```
try {
    // Code
} catch (Exception $Ex) {
}
```

**Comment by linc** [comment]
I am noticing lots of class files that have the file docblock but no class docblock are having their clear line before the class declaration removed, turning the file docblock into a class docblock. I feel like this is a good phase-2 fix to make when I adjust the file docblocks later so I'm inclined to let that slide.

**Comment by linc** [comment]
Another great one from our faulty doc formatting: `@param string $Username .` (the period being moved away from the variable).

**Comment by tburry** [comment]
Horizontally aligned array assignments are not part of our standard and we hates them.

**Comment by linc** [comment]
What's the verdict on line breaks in the middle of HTML tags? I don't like it much but I think it's doing that to obey our max line length, and it seems like it's gonna be a lot of trouble to undo. Examples:

/git/vanilla/applications/dashboard/views/activity/all_rss.php line 18.
/git/vanilla/applications/dashboard/views/authentication/choose.php line 5.
/git/vanilla/applications/dashboard/views/default.master.tpl "Powered by Vanilla".
/git/vanilla/applications/dashboard/views/deverror.master.php line 117.
/git/vanilla/applications/dashboard/views/entry/signout.php line 8.
/git/vanilla/applications/dashboard/views/home/filenotfound.php line 6.
/git/vanilla/applications/dashboard/views/log/edits.php line 3.
/git/vanilla/applications/dashboard/views/log/moderation.php line 3.
/git/vanilla/applications/dashboard/views/log/record.php line 3.
/git/vanilla/applications/dashboard/views/message/index.php line 13 & 15.

**Comment by linc** [comment]
In `structure.php` files I notice it is removed the space between chained method calls and the end-of-line comments, e.g.:

     ->Column('Something', 'int')// no space before the slashes now

Weird but not that bad I guess?

**Comment by linc** [comment]
/git/vanilla/library/core/class.request.php 847-849 bracing derps didn't get fixed.

**Comment by linc** [comment]
/git/vanilla/library/core/functions.general.php 2222 same thing

**Comment by linc** [comment]
This is the rest of the mid-HTML element breaks I found for the record but I'm inclined to leave them.

/applications/dashboard/views/modules/trace.php 67
/applications/dashboard/views/modules/userphoto.php 34
/applications/dashboard/views/profile/activity_rss.php 15-19
/applications/dashboard/views/profile/picture.php 69
/applications/dashboard/views/profile/thumbnail.php 23
/applications/dashboard/views/settings/bans.php 3
/applications/dashboard/views/settings/email.php 12, 26
/applications/dashboard/views/settings/registration.php 59
/applications/dashboard/views/setup/configure.php 40
/applications/dashboard/views/social/connection_functions.php 46
/applications/vanilla/views/categories/table.php 12
/applications/vanilla/views/discussions/index_rss.php 16
/applications/vanilla/views/drafts/drafts.php 18
/applications/vanilla/views/modules/helper_functions.php multiple
/applications/vanilla/views/settings/advanced.php 111, 119
/applications/vanilla/views/settings/deletecategory.php 26
/applications/vanilla/views/settings/floodcontrol.php 15
/plugins/Flagging/views/flagging.php 48, 81
/plugins/Quotes/views/quotes.php 9
/plugins/Tagging/views/taggeddiscussions_rss.php 5
/plugins/Tagging/views/tagging.php 99

**Comment by linc** [comment]
The Spacening is cleared for docking.

**Comment by tburry** [comment]
We're going to leave the max-line length issues. I think we can be okay without a max line length as we go forward though.

**Pull request merged**
