### PR TITLE
Include autoloader using PATH_ROOT

### PR DESCRIPTION
**Pull request by jfarthing84**
Use PATH_ROOT instead of __DIR__ to include the composer autoloader.

### CODE REVIEW

**Comment by DaazKu** [comment]
Is there any reason in particular that made you do that change?

**Comment by jfarthing84** [comment]
It is required to run Vanilla from a subdirectory, otherwise, one must copy `environment.php` along with `index.php` into the top-level directory.

**Comment by charrondev** [comment]
I'm still not understanding the workflow here, is this for the case where you're using Vanilla as a composer dependency?

**Comment by charrondev** [comment]
@jfarthing84 @chrisvanpatten Do either of you have the justifying use case for this change?

**Comment by jfarthing84** [comment]
Other than the fact that PATH_ROOT is used for every other include in that file?

> It is required to run Vanilla from a subdirectory, otherwise, one must copy environment.php (along with index.php) into the top-level directory just to change that path.

**Comment by charrondev** [comment]
The closest relavent thing I could find around this is this comment: https://github.com/vanilla/vanilla/pull/5674#issuecomment-309058410

@linc Where does this facilitate/break any of these use cases?

**Pull request merged**
