### PR TITLE
Hotfix/php 5.3 compatibility

### PR DESCRIPTION
**Pull request by hgtonight**
This adds a userland implementation of array_column for PHP < 5.5. It is recommended per the PHP documentation: http://php.net/manual/en/function.array-column.php

I also removed some more short arrays.

### CODE REVIEW

**Comment by hgtonight** [comment]
This fixes #3200

**Comment by linc** [comment]
fyi, the same array_column substitute is in `master` in `core/functions.general.php` :)

**Comment by hgtonight** [comment]
@linc I was looking for it, but didn't find it.

Good eye :)

**Comment by linc** [comment]
I cleaned this up to match that implementation so it doesn't trip us up with extra file loading at odd spots.

**Comment by hgtonight** [comment]
:+1:

**Pull request merged**
