### PR TITLE
Tweak the .gitignore

### PR DESCRIPTION
**Pull request by tburry**
- Add two missing plugins: recaptcha and stubcontent.
- Sort the plugins.

### CODE REVIEW

**Comment by DaazKu** [comment]
I did that as part of my another PR https://github.com/vanilla/vanilla/pull/5542/commits/354883ef05376746feb9c7ad0ae9e13116232e81
Want me to revert the change in favour of this PR?

**Comment by tburry** [comment]
No that's fine. Another argument in favor of smaller PRs don't you think?

**Comment by DaazKu** [comment]
Yes. Definitely. I'm working on that!

**Comment by DaazKu** [comment]
I had to rebase the PR so let's keep this one!

**Pull request merged**
