### PR TITLE
Fix rotation issue with iPhone uploads

### PR DESCRIPTION
**Pull request by webstey**
As per http://vanillaforums.org/discussion/28683/images-are-rotated-when-resized , added rotation of image files if EXIF rotation tags are present.

### CODE REVIEW

**Comment by linc** [comment]
YESSSSSSSSSSS

**Comment by webstey** [comment]
I guess it worked for you too linc?  :)  FWIW, I've been using this on my forum since sometime in December with no complaints.

**Comment by linc** [comment]
Haven't tested it yet, but this is a known grievance with core and a personal pet peeve. I've resorted to using Preview to rotate photos 90 degress and back again & save it to make sure it uploads correctly.

**Comment by linc** [comment]
I tried this out and it didn't actually solve the problem for me. I attached my sample photos over here if you want to dig further. http://vanillaforums.org/discussion/comment/224734/#Comment_224734

**Comment by bleistivt** [comment]
@webstey could you try checking for both $exif['Orientation'] and $exif['IFD0']['Orientation']?

**Comment by webstey** [comment]
Sorry for flaking off here; I've been busy with family etc etc.  Going to take a look now.

**Comment by linc** [comment]
8 days doesn't even rate for "flaking off" around here, lol. I know how it goes.

**Comment by webstey** [comment]
Interesting.  I uploaded the 4 photos you posted at VF with the following results:

- using ImageUpload, all 4 photos are rotated properly.  
- using FileUpload, the thumbnails are rotated properly, but when I click on them to view the originals, they are *not* rotated.

Any ideas?

**Comment by webstey** [comment]
This is the case for both your test images, and the test images from my user.  His were from an iPhone 5s, yours from iPhone 6 (according to the exif tags).  Both used the 'Orientation' exif tag.

**Comment by bleistivt** [comment]
ImageUpload uses Gdn_UploadImage->SaveImageAs()
Fileupload uses Gdn_Upload->SaveAs()

oh, and I just stumbled upon a snippet using the IDF0 subarray, which is the reason i just posted this here. Take all the time you need.

**Comment by bleistivt** [comment]
oh, and for the thumbnails FileUpload uses SaveImageAs, which seems to be the reason for this.

I'd argue that for a generic fileupload, not rotating the image is ok, since one may be interested in the original file, but as it's primarily used to attach images to comments, proper orientation would be expected by most users.

**Comment by webstey** [comment]
Thanks @bleistivt !  Very helpful.  I am going to make the images get rotated by FileUpload.  2 questions for you and @linc : 
1. Should I add this to the fix, or should I leave it out as per @bleistivt comment?  I wasn't sure which you thought I should do :)
2. Presuming I am going to make FileUpload rotate images, should I put this in the FileUpload plugin code, or in the core SaveAs function?  My guess would be the former.

**Comment by webstey** [comment]
Finally, @bleistivt do you have a sample photo that uses the IDF0 tag handy?

**Comment by bleistivt** [comment]
lincs photos actually seemed to have that. I used an online exif tool:

http://exifdata.com/

**Comment by webstey** [comment]
Ah, I was using exiftool - and I just looked up what IFD0 meant, so I've unconfused myself there.

I think the solution may lie in calling SaveImageAs in the FileUpload plugin if it's an image, instead of doing the straight up copy.  Weird that it doesn't actually use the SavaAs function already?  I'm not sure what the effect of the FireAs() function is, but it doesn't change anything if I change it.

**Comment by bleistivt** [comment]
FireAs() just changes the Controller Name of the Hook that will be called.

The class is called "FileUploadPlugin" which would make the event <code>FileUploadPlugin_SaveAs_Handler</code>, but the intention seems to be for plugins that handle the <code>Gdn_Upload_SaveAs</code> Event to also hook into this.

Plugins can Handle this event as <code>Gdn_Upload_SaveAs_Handler()</code> just like with normal fileuploads.

That doesn't explain why the plugin is not using the SaveAs() function. Could be possible, that it uses it's own MediaModel in some way that Gdn_Upload would not allow.

**Comment by webstey** [comment]
I've got it partly figured out, but think I may have noticed a bug in my edit to SaveImageAs - I'm not adjusting the image height/width after rotating. I haven't figured out if some other code is doing it after the fact yet.

**Comment by webstey** [comment]
Update: yep, I was right.  ImageUpload doesn't seem to do anything with height/width after calling SaveImageAs, so it works just dandy.  However, FileUpload's thumb generator seems to add in CSS to size the image, so 90 or -90 rotated images were stretched.  I made SaveImageAs return the new height and width so the thumbnail generator (or any code using it) can get the proper dimensions.

I seem to have made it work, rotation, new dimensions, and all!  I had to edit class.fileupload.plugin and class.uploadimage.php.  Now I just have to figure out how to add my changes to the PR.

**Comment by webstey** [comment]
OK, I've added my changes to class.uploadimage.php.  Can I somehow add my changes class.fileupload.php to this PR, even though it's in the addons repo?

**Comment by bleistivt** [comment]
No, that will have to be a separate PR.

Great! Can't wait to have this in the app, so I don't have to manually rotate images of my users on the server anymore.

**Comment by webstey** [comment]
I made the PR (#182) and referenced this issue.  Hopefully that works?

**Comment by bleistivt** [comment]
Github will autolink that if you just paste the uri here.

**Comment by webstey** [comment]
https://github.com/vanilla/addons/pull/182

**Comment by webstey** [comment]
OK, thank @bleistivt !  I think I've got it now.

https://github.com/vanilla/vanilla/issues/2345

**Pull request merged**
