### PR TITLE
Fix IpEncodeRecursive function

### PR DESCRIPTION
**Pull request by DaazKu**
There's a bug with the `IpEncodeRecursive` function since #7923. Here is a PR with basic unit test to demonstrate the issue.

- [x] Fix IpEncodeRecursive function
- [ ] Provide more unit tests with objects and nested cases.

### CODE REVIEW

**Comment by tburry** [comment]
Can you make sure this is assigned to someone and completed @linc? I'm closing my browser tab and after that I've forgotten about it.

**Comment by linc** [comment]
Yes, it's slated for the next support sprint.

**Comment by cchabilall83** [comment]
Tests are failing on my local

**Comment by topcheese13** [comment]
Tests are now passing for me (after merging master in the feature branch).

**Pull request merged**
