### PR TITLE
Merge hero image plugin into core

### PR DESCRIPTION
**Pull request by charrondev**
Working towards https://github.com/vanilla/support/issues/361#issuecomment-563501474

- Merges the hero image plugin into core.
- Adds unit tests.

**Delete Hero Image plugin**

I've deleted the hero image plugin. Instead a banner image is now just part of Vanilla.

- Adds banner image upload to general appearance.
- Adds banner image upload to category.
- A new DB column has been added to the category plugin.

**Class Migration**

- `HeroImagePlugin` -> `Vanilla\Dashboard\Models\BannerImageModel` (alias added).
- All plugin functionalities -> The original forms that were being hooked.
- `{hero_image_link}` -> `{banner_image_link}` (old smarty tag deprecated).

**Content Migration**

- Rename category DB column `HeroImage` -> `BannerImage`.
- Migrate existing `Garden.HeroImage` configs to `Garden.BannerImage`.
- Remove old configs (and plugin config reference).

**Keystone Update**

Technically everything was still working fine before updating keystone, but a bunch of deprecation warnings were coming out.

- Remove all checks for `HeroImagePlugin` from themehooks.
- Theme now just uses `{banner_image_url}` tag since it's always available.
- Move the theme options config view into a twig template instead of echos.
  - Wording has been updating for the new "Banner Image" wording. See translation updates here: https://github.com/vanilla/locales/pull/241
  - None of the existing dashboard strings were actually in transifex.

### CODE REVIEW

**Comment by tburry** [comment]
I'm a bit foggy on the original functionality here so it will be kind of difficult for me to review here. What did the original addon do?

**Comment by charrondev** [comment]
> I'm a bit foggy on the original functionality here so it will be kind of difficult for me to review here. What did the original addon do?

It:

- Added a custom settings page with a single file upload for setting a "default" site banner image.
- Added a column on the category DB, and hooked the category form to allow uploading an image per-category.
- Had a method get the "current" banner image for the page, and allowed using that as a smarty tag. Unfortunately, because the smarty function was only conditionally going to work if the plugin was on, and it's not on by default, it caused a good bit of support. Sites would fatally crash if the plugin got turned off. As a result keystone needed a custom integration with it.

**Now**
- Global default moved to the branding page.
- Wording re-adjusted to be "Banner Image"  instead of "Hero Image".
- Category form stuff moved out of a plugin and directly into the form.
- Keystone now just uses the smarty function. Custom integration has been scaled back.

**Comment by slafleche** [comment]
@charrondev did you do that last change you wanted or this is ready to go?

**Comment by charrondev** [comment]
@slafleche I put back the Keystone `setData()` call for compatibility with existing master views.

@tburry I know you had some misgiving about the DB migration piece, so I added some tests of my changes in `vanilla/settings/structure.php`.

**Pull request merged**
