### PR TITLE
Fix initial permissions during site spawning

### PR DESCRIPTION
**Pull request by linc**
* Add second permission setup call in structure so it is triggered when called remotely.
* Minor cleanup in code I read while evaluating this issue.

### CODE REVIEW

**Comment by tburry** [comment]
I don't like that call in vanilla. What about conversations and everything else in the future?

**Comment by tburry** [comment]
Try putting the check in `UpdateModel->runStructure()`.

**Comment by tburry** [comment]
Bonus points for conditionally registering a handler using `Gdn::pluginManager()->registerHandler()` in dashboard's structure. We've never done this before, but it's the future.

**Comment by linc** [comment]
Honestly putting it in Vanilla's structure instead of Dashboard's was a mistake; I lost track after testing several variations on how to do this. I'll have a look at those other solutions.

**Comment by tburry** [comment]
I appreciate your honesty. The house of lies must be burned down.

**Comment by linc** [comment]
:fire: :house_with_garden: :fire: :vertical_traffic_light: :fire_engine:

**Comment by linc** [comment]
Can you elaborate on this `Gdn::pluginManager()->registerHandler()`? I'm not following what you're laying down. It seems like I'd already have to know what things I'm looking for installed (Vanilla, Conversations) to do that rather than things actually hooking.

**Comment by kaecyra** [comment]
Tested on cl111, works as expected.

**Pull request merged**
