### PR TITLE
Backport various fixes to release/2.8

### PR DESCRIPTION
**Pull request by charrondev**
Backports the following PRs to `release/2.8`. I've selected all the security fixes, and various bug fixes that seemed significant.

## Security

-  https://github.com/vanilla/vanilla-patches/pull/478 - Fix stored XSS when deleting a tag
- https://github.com/vanilla/vanilla-patches/pull/477 - InThisDiscussion Plugin: Fix Xss in username field
- https://github.com/vanilla/vanilla-patches/pull/480 - Tagging: Fix Adding tags to discussions without proper permission
- https://github.com/vanilla/vanilla-patches/pull/479 & https://github.com/vanilla/vanilla-patches/pull/482 - Check Discussion permissions when flagging a discussion
- https://github.com/vanilla/vanilla-patches/pull/492 - Fix: Bypassing trusted domains to post links using Right-to-left unicode character
- https://github.com/vanilla/vanilla-patches/pull/497 - Fix XSS at add user/reveal password
- https://github.com/vanilla/vanilla-patches/pull/496 - Fix: manipulating conversationID can shut down further new conversations

## Keystone Fixes

- https://github.com/vanilla/vanilla/pull/8412
  - Fix responsive theme support for keystone.
  - Fix keystone `NewFlyouts` feature flag not directly tied to the theme being enabled.
  - theme-boilerplate `ThemeHooks` removed. No longer necessary.
  - Keystone no longer forces itself as the mobile theme.
- https://github.com/vanilla/vanilla/pull/8473 - Fix keystone javascript error for signed out users (preventing refresh on signin).
- https://github.com/vanilla/vanilla/pull/8475 && https://github.com/vanilla/vanilla/pull/8508 - Fix Advanced Editor flyouts on mobile with keystone

## Rich Editor 

- https://github.com/vanilla/vanilla/pull/8414 - Fix clearing of rich editor for conversations and activity
- https://github.com/vanilla/vanilla/pull/8397 - Fix formatting of notifications & emails for the following post formats:
  - Rich
  - BBCode
  - Markdown
_Previously these post formats were being sent out "raw" in notifications & emails. This looked particularly bad for the Rich format._
- https://github.com/vanilla/vanilla/pull/8516 - Fix undo/redo actions for embeds while creating rich posts
- https://github.com/vanilla/vanilla/pull/8492 & https://github.com/vanilla/vanilla/pull/8540 - Fix a bug causing partially loaded rich embeds from crashing the page.

## Pockets

- https://github.com/vanilla/vanilla/pull/8455 - Pockets: Fix typo in pockets permissions
- https://github.com/vanilla/vanilla/pull/8431 - Fix casing of pockets CSS class location

## Other

- https://github.com/vanilla/vanilla/pull/8502 - Fix installation on windows.
- https://github.com/vanilla/vanilla/pull/8447 - Put back missing cache folder
- https://github.com/vanilla/vanilla/pull/8401 - Make audit only block builds in cron jobs (_needed to make backports pass travis_)
- https://github.com/vanilla/vanilla/pull/8529 - Add scripts for bumping release versions and making a clean release (_For making the release_)

### CODE REVIEW

**Comment by charrondev** [comment]
I'm putting a hold on this because there's one or 2 more I'd like to backport in.

**Comment by linc** [comment]
@R-J @hgtonight @austins  FYI this is what we're doing for the 2.8.1 release if you have any other patches that are important + constrained in scope.

**Comment by austins** [comment]
Would it be good to backport 7ae2fd734f7941c174f491d734d56f72079354b7? It would help developers and users on Windows smooth out the install process.

**Comment by charrondev** [comment]
@austins Added.

Still a couple more to add, but we're waiting for them to get merged to master first.

**Pull request merged**
