### PR TITLE
Basic composer integration

### PR DESCRIPTION
**Pull request by tburry**
Add basic composer integration to Vanilla. This integration just adds composer autoloader support, but will be the basis for much deeper integration in the future.

### CODE REVIEW

**Comment by tburry** [comment]
Let's hold off until 2.2 starts in earnest for this one.

**Comment by tburry** [comment]
I'll redo this PR after the spacening.

**Comment by bleistivt** [comment]
Are you planning to remove the core autoloader and (in the future) libraries from the repo, or are you going to update those locally and commit them to the repository?

**Comment by tburry** [comment]
We can't use composer for addon classes because they shouldn't always be available.

I am planning on an autoloader rewrite in the future. We are going to remove the ability to have a context aware autoloader which will simplify and speed it up somewhat.

**Comment by linc** [comment]
This is ready to go, but I'm unclear how we're dealing with this in our deploy process.

**Comment by tburry** [comment]
Staged this to cl211.

**Comment by tburry** [comment]
Rebased to current master.

**Pull request merged**
