### PR TITLE
Add missing events to edit post view to match post comment form

### LINKED ISSUE #2822: post/editcomment.php lacks the events that post/comment.php has
https://github.com/vanilla/vanilla/blob/fd534663270327d5a78fc4173e07fd0215cd844a/applications/vanilla/views/post/editcomment.php

https://github.com/vanilla/vanilla/blob/fd534663270327d5a78fc4173e07fd0215cd844a/applications/vanilla/views/post/comment.php

As far as I know this has been an issue since editcomment was introduced. 

I think it would be a good candidate for 2.2 IMO

Workaround view overrides.

### PR DESCRIPTION
**Pull request by x00**
Closes #2822

### CODE REVIEW

**Comment by linc** [comment]
You need to update your fork first. You're reverting our recent space & casing changes here too.

**Comment by x00** [comment]
I fetched upstream, what changes?

**Comment by x00** [comment]
oh sorry didn't understand, now I got it.

**Comment by x00** [comment]
done

**Comment by linc** [comment]
The indents are still at 3-space instead of 4-space. That's why the diff makes it look like you're deleting it all and re-adding it all instead of just inserting a couple lines.

**Comment by x00** [comment]
done

**Pull request merged**
