### PR TITLE
Add sanitization and related tests for embed blots

### LINKED ISSUE #7200: Add sanitization tests for server-side embed blot class
Input sanitization tests for Quill rendering classes need to be extended to include the embed blot.

### PR DESCRIPTION
**Pull request by initvector**
This update adds testing capabilities for Vanilla's external embed blot rendering.

1. `Gdn_Format::cssSpecialChars` has been added to encode special CSS characters.
1. `Gdn_Format::cssSpecialChars` is used to sanitize the background property in the `LinkEmbed` class.
1. `CSSInjectionTrait` has been added for testing CSS injection in the blot sanitization test suite.
1. Tests have been added for ensuring server-side embed blot content has been sanitized.
1. Adds `cssSpecialChars` to Dashboard JavaScript utils.
1. Sanitize background image in `renderLinkEmbed` JavaScript function with `cssSpecialChars`.

The list of CSS special characters was boosted from [CSS character escape sequences](https://mathiasbynens.be/notes/css-escapes#css).

Closes #7200

### CODE REVIEW

**Comment by DaazKu** [comment]
Guys.. This fix breaks URLs `https\00003a\00002f\00002fi\00002eimgur\00002ecom\00002f3zo1Frp\00002ejpg\00003ffb` is not a valid URL. The CSS engine fortunately decode it before trying to use it but it's breaking normal functionalities:

screen shot 2018-05-30 at 2 32 59 pm
screen shot 2018-05-30 at 2 33 56 pm
`https://dev.vanilla.localhost/en/discussion/17/auth-required/https/00003a/00002f/00002fi/00002eimgur/00002ecom/00002f3zo1Frp/00002ejpg/00003ffb`

**Comment by initvector** [comment]
> Guys.. This fix breaks URLs [...]

The CSS is rendering like it should, but I can confirm dev tools isn't playing well with escaped CSS (at least for URLs).

**Comment by DaazKu** [comment]
> The CSS engine fortunately decode it before trying to use it

**Comment by initvector** [comment]
Confirming that "This fix breaks URLs " and "breaking normal functionalities " is currently limited to dev tools not playing well with them.

**Comment by DaazKu** [comment]
> Confirming that "This fix breaks URLs " and "breaking normal functionalities " is currently limited to dev tools not playing well with them.

Low priority fix :D

**Comment by charrondev** [comment]
This will likely end up as a non-issue because we will not be able to allow background images in CSS from user-content due to https://github.com/vanilla/vanilla/issues/7268#issuecomment-392593483

**Pull request merged**
