### PR TITLE
Let class messages add() accept a "Subject" parameter

### PR DESCRIPTION
**Pull request by R-J**
By now only the recipient can be "pre-filled" by adding its name to "/messages/add/recipient". This enhancement allows using "/messages/add/recipient/subject of the message"

### CODE REVIEW

**Comment by linc** [comment]
What do you think about this issue and how it impacts this feature request? https://github.com/vanilla/vanilla/issues/4220

**Comment by R-J** [comment]
@linc it doesn't interfere with [this PR](https://github.com/vanilla/vanilla/pull/4288) :wink:

**Comment by linc** [comment]
I mean the broader issue of accepting URL parameters as potentially misleading page text.

**Comment by R-J** [comment]
Sorry, I do not understand/see any issue. In what way would /messages/add/recipient/subject be any different to e.g the mailto link?
http://www.w3schools.com/tags/tryit.asp?filename=tryhtml_link_mailto

**Comment by linc** [comment]
It's a link having the ability to pre-fill text on the page, which could be mistaken for official UI text. Therefore it could misdirect a user to perform an action they shouldn't.

**Comment by R-J** [comment]
You can find my answer [here](https://vanillaforums.org/post/discussion?Name=I%20do%20not%20see%20a%20problem)  :wink:

**Comment by R-J** [comment]
But without joking: adding text to form is easy like the above example shows. It might be prevented if there is a more restrictive GET and POST separation, but maybe not - I don't know much about that.

If it were a bigger issue it would have been addressed more often and I have  never read anything about any dangers about that.

Having "/messages/add/recipient/subject of the message" looks nicer than "/messages/add/recipient?Subject=subject of the message" but I do not think anybody would really notice the difference

**Pull request merged**
