### PR TITLE
Use safe unlink and fix doc typo

### PR DESCRIPTION
**Pull request by hgtonight**
Fix a typo on the recently added safeUnlink function documentation and use it in the isWritable function as well.

### CODE REVIEW

**Comment by linc** [comment]
Should just need a quick de-conflict.

**Comment by DaazKu** [comment]
It was a stupid trailing whitespace loll

**Comment by DaazKu** [comment]
@hgtonight the CLA bot is not happy :(

**Comment by hgtonight** [comment]
Done.

**Pull request merged**
