### PR TITLE
Refactor model form filtering

### PR DESCRIPTION
**Pull request by tburry**
- Add the property Gdn_Model->filterFields to control which fields get filtered on Gdn_Model->save().
- Add convenience methods to manipulate Gdn_Model->filterFields.

The idea behind this functionality is allowing more control on form filtering.

### CODE REVIEW

**Comment by mtschirs** [comment]
What do you think about switching to explicit whitelisting (was a suggestion from @bleistivt)?

**Comment by tburry** [comment]
Explicit whitelisting is something we are going to do for v2 of our API, but aren't currently planning for the rest of the app.

**Comment by mtschirs** [comment]
You should really consider whitelisting POST fields that are written back to the database. Whitelisting could e.g. have prevented the admin registration vulnerability earlier this year.

**Comment by tburry** [comment]
It has been considered and will be implemented in v2 of our API. However, this PR is not the place for it.

**Comment by mtschirs** [comment]
Sorry if I was not clear enough. I was not talking about the API, but about model form filtering. This PR refactors model form filtering by giving subclasses of Gdn_Model the ability to modify the blacklist. However, in my opinion, a whitelisting approach offers advantages over this blacklisting approach, i.e. instead of offering subclasses the ability to modify the blacklist I recommend offering subclasses the ability to modify a whitelist.

If that is what you already understood from reading my comment, then all is well. I was just confused by you bringing up the API here.

**Pull request merged**
