### PR TITLE
Exploding HOST (localhost:9090 => [localhost, 9090] and cutting out the ...

### PR DESCRIPTION
**Pull request by linc**
...port results in incorrect paths when running Vanilla Forums locally on any post other than 80

### CODE REVIEW

**Comment by linc** [comment]
This was lost into the void of `develop` branch. See #1386

**Comment by tburry** [comment]
This is the wrong fix. Host should return the host. Not the host and the port.

**Comment by tburry** [comment]
We even have `Gdn_Request->HostAndPort()` which should be used instead of `Gdn_Request->Host()` where appropriate.

**Comment by onurguzel** [comment]
I have encountered a malfunction related to this issue. I am running nginx, and in the `Gdn_Request->_LoadEnvirontment()` method obtains host information via `$_SERVER['HTTP_HOST']` which has a value of `host:port`. This causes invalid host information to be stored in environment (and bad URLs such as `http://host:port:port/index.php?p=/dashboard/setup`

I think the proper way to fix this is modifying the `_LoadEnvironment()` method. Should I make changes and create a new pull request?

**Comment by linc** [comment]
@onurguzel Please start a new discussion on the forum with your version number for troubleshooting help. I suspect you're running an older version of Vanilla.

**Comment by onurguzel** [comment]
@linc this problem still exists in 2.1.10, which is the latest version. but i saw that it has been fixed ( #2170  ) months ago in master.

**Comment by linc** [comment]
Thanks for the heads up! We're going to be doing 2.2 beta shortly so hopefully it won't need to get backported.

**Pull request closed without merging**
