### PR TITLE
Fix error handling in entry AJAX forms

### PR DESCRIPTION
**Pull request by charrondev**
Fixes https://github.com/vanilla/vanilla/issues/8862

Starting with https://github.com/vanilla/vanilla/pull/8763 our entry pages are submitting through AJAX. Unfortunately there were some bugs in error handling.

This PR.

- Fixes the ajax submission logic.
- Adjust all entry forms to have consistent data structure and explictly put `AjaxForm` on their containers.
- Allow displaying of form errors returned from the ajax submission.

**Note on signin.php**

The `signin.php` view was particularly complicated because it contained 2 forms, and returning back an error rendered the full view. Therefor every error would cause both the forms to be rendered and returned back, while our old ajax form submit functionality expects only 1 form to be rendered as part of the view.

We already had a separate view and routing for the "Forgot?" password view though, so I've removed the kludgy and inaccessible javascript that toggled the 2 views and now the 2 forms are just on different pages.

This PR will need to be followed up with updating any view overrides in custom themes.

### CODE REVIEW

**Comment by nervoustwit** [comment]
My first tests it works great. The only place I found that it doesn't work is on /entry/password

**Comment by charrondev** [comment]
@nervoustwit Thanks I probably made a mistake there.

**Comment by charrondev** [comment]
@nervoustwit Are you sure? I can't seem to reproduce this issue on the password page.

**Comment by nervoustwit** [comment]
> @nervoustwit Are you sure? I can't seem to reproduce this issue on the password page.

OK my bad. I just looked again (cleared cache, etc.)  and it works.

**Pull request merged**
