### PR TITLE
Foundation Theme - Iteration 3

### PR DESCRIPTION
**Pull request by slafleche**
Implements design feedback.

~~@charrondev the search we added on the forum side shows the suggested results, but i can't actually do the search...~~

~~Requires: https://github.com/vanilla/internal/pull/2215~~
Related: https://github.com/vanilla/multisite/pull/339

Closes: https://github.com/vanilla/vanilla/issues/10042
Closes: https://github.com/vanilla/vanilla/issues/9879
Closes: https://github.com/vanilla/vanilla/issues/10016

### CODE REVIEW

**Comment by charrondev** [comment]
A few visual issues, looking form the lavendar moon perspective (may apply to other themes though).

## Discussion/Comment view

image

- [ ] User content links don't use the link color.
- [ ] Embed link hover color is not respecting the link hover color.
- [ ] User rank tags have the incorrect border color.
- [ ] Border color of the "signatures" section doesn't respect the theme border color.
  - Bottom margin on this separator seems to be missing.

## KB Banner

image

- [ ] Search button looks odd
  - Border color seems off.
  - Extra colored border appearing.
  - Title color doesn't seem to be set to a good contrast
- [ ] Tile bottom border radii aren't consistent with top ones.

## Site Navigation

|Forum|KB right nav|Kb Left nav|
|---|---|---|
|image|image|image|


- [ ] Font weight seems different.
- [ ] Font size seems different.
- [ ] Link color doesn't seem to have sufficient contrast. something like the button primary color seems more appropriate.
- [ ] Only the active site nav link should have the link color unless hovered.
- [ ] Collapsible headings in the nav should not ever have a link color.
- [ ] KB left nav arrows don't use the item color.
- [ ] There seems to be some regression in the font-weight of the collapsible KB items.
- [ ] Font weights/sizes don't seem consistent from KB to forum.

**Comment by slafleche** [comment]
@charrondev ready for round 2.

**Comment by charrondev** [comment]
## KB Nav

image

Missing:
- [ ] Hover, active, header boldness

## Colour generation

- [ ] Our primary colour generation seems to have flipped. I'm getting a fluorescent blue with our defaults.

image

## Category Following

image

- [ ] Active item has a solid background. Is that supposed to happen?

## Banner

image

- [ ] Outer border still showing up (see the blue tint on the right).
- [ ] Inner border styles when focused are missing.

## Community Dropdowns

image

- [ ] Font size is too small

image

- [ ] **_Opening a dropdown makes the rest of the page disappear ☢️☢️☢️**

## DiscussionList

image

- [ ] Tags have underline, then lose it on hover. Kind of weird.

## Discussion/Comments

image

- [ ] Username has an underline now.

## Rich Editor

image

- [ ] Has a colored outline on hover, but loses it on focus

**Comment by slafleche** [comment]
@charrondev "Misaligned to description" what do you mean?

**Comment by charrondev** [comment]
|Mock|Actual|Description|
|---|---|---|
|image|image|Standard button styles no longer match our mockups. Supposed to be a standard primary color and border matching background|
|image|image|Generation of this secondary(?) hover color seems to be a little dark for primary buttons. This is most obviously seen in this multibutton|

**Pull request merged**
