### PR TITLE
Add russian letter "И" to function url()

### PR DESCRIPTION
**Pull request by R-J**
The russian letter "И" was missing from class Formats `protected static $_UrlTranslations`. Closes  https://github.com/vanilla/vanilla/issues/5068

### CODE REVIEW

**Comment by linc** [comment]
screen shot 2017-01-29 at 12 09 02 pm

**Comment by linc** [comment]
I think you've perhaps actually found the root of the issue: It was already in there twice.

**Comment by R-J** [comment]
It is not in the 2.3 release, but it double in the master branch. Seems like that issue has been addressed before, but handled wrong.

**Comment by R-J** [comment]
Seems to come from here: https://github.com/vanilla/vanilla/commit/7762cdb854f0ddd61e1eb2075202f4d120f97b99

**Pull request closed without merging**
