### PR TITLE
Add meta tags for Twitter cards

### PR DESCRIPTION
**Pull request by DaazKu**
Fix https://github.com/vanilla/vanilla/issues/4719

### CODE REVIEW

**Comment by DaazKu** [comment]
Sorry for the lack of details:

* Are you certain you can combine tags for double-duty like this (name on top of property)? Is any other software doing this?
  - Yes
* Did you BC test this with Facebook?
  - Yes
* You've added `twitter:image` here without doing any of the checks to see if the found image is within their guidelines for dimensions, size, or context (not a logo or avatar). This sort of qualifications rabbit hole is what I was concerned about.
  - Their documentation state that images over 1mb (or 2 depending where you read) will not be taken into account. I'm pretty sure that checking the size of each images on the page load is a big NO NO. I would let the twitter bot just fail here. I can put a comment in the code though.
* Do we want non-discussion content embedding as a Twitter card? That seems problematic, but there's no consideration of it here. You paste a link to the Activity page, it grabs some random image from the page (probably a tiny badge that gets way scaled up?) and "..." as a description. That's a bad experience.
  - Why not. We already do that with open graph?
  - The '...' is added because a description is needed. If we do not add something as the description the card won't be generated. (Post with only an image for example)

**Comment by linc** [comment]
There are also dimension specs and context specs (which I mentioned above). Specifically, making sure the logo isn't the grabbed image would be pretty trivial since we're doing that in a separate logic block already.

I don't see a problem with *not* using a Twitter card when the content doesn't make sense to have one. The difference between this and the OpenGraph tags is that OG is just describing some content that could be highlighted; the Twitter card markup is a command to format it in a particular way. Therefore we should give thoughtful commands and not just shrug and see what happens. It at least makes halfway sense to have a blank post with an image but no text to get a "..." to force a card that shows the image. The Activity page example I used (or any other random page like that) it makes very little sense.

**Comment by DaazKu** [comment]
Twitter cards are now generated only when relevant. 
- Discussions only.
- Generate a summary card if the discussion has no images.
- Put '...' as the description if the discussions has a relevant image but no text.

The dimension constraint are a SHOULD so we will not try to validate them.
The size constraint is a MUST but I think that it would be stupid check an image size remotely on every page load. **I could do a check if the image is local but, again, meh...**

**Comment by linc** [comment]
I agree checking image size is above and beyond what we want to do here.

**Comment by DaazKu** [comment]
A summary_card is a title and a description. It does not make sense to "pad" the description there.
A summary_large_image can be worth seeing without description since the title and the image may convey enough information for the card to be "valid"

The code went from:
```php
if ($hasImage) {
    $twitterCardType = 'summary_large_image';
} else {
    $twitterCardType = 'summary';
}
```
to
```
if ($hasRelevantImage) {
    $twitterCardType = 'summary_large_image';
    if (!$Description) {
        $Description = '...'; // Let's force a description since a card needs one.
    }
} else {
    if ($Description) {
        $twitterCardType = 'summary';
    }
}
```

and I did not notice that it could be undefined after the change..

**Comment by linc** [comment]
> A summary_card is a title and a description. It does not make sense to "pad" the description there.

Does it make sense to then add a blank twitter:description meta tag?

**Comment by linc** [comment]
If you're going to make a non-obvious choice like only forcing a description for one type of card, it makes sense to leave a code comment so the next dev isn't left scratching their head about the asymmetry of the code.

**Comment by DaazKu** [comment]
I updated the logic of the code and added comments.
I also made sure that $Title has a value since it is required by every twitter cards

**Pull request merged**
