### PR TITLE
Remove execute permissions on all files (chmod -x)

### LINKED ISSUE #1530: File Permissions
For some reason a lot of files are `-rwxrwxr-x` instead of just `-rw-rw-r--`.

```bash
$ ls -ltr applications/dashboard/controllers/
total 372
-rwxrwxr-x 1 arian arian  1278 Feb 12 16:46 class.plugincontroller.php
-rw-rw-r-- 1 arian arian  5676 Feb 12 16:46 class.authenticationcontroller.php
-rwxrwxr-x 1 arian arian 12339 Feb 16 20:44 class.activitycontroller.php
-rwxrwxr-x 1 arian arian 19806 Feb 16 20:44 class.utilitycontroller.php
-rwxrwxr-x 1 arian arian 24992 Feb 16 20:44 class.usercontroller.php
-rw-rw-r-- 1 arian arian  4006 Feb 16 20:44 class.statisticscontroller.php
-rw-rw-r-- 1 arian arian  3729 Feb 16 20:44 class.socialcontroller.php
-rw-rw-r-- 1 arian arian 16368 Feb 16 20:44 class.setupcontroller.php
-rw-rw-r-- 1 arian arian 47176 Feb 16 20:44 class.settingscontroller.php
-rwxrwxr-x 1 arian arian  1604 Feb 16 20:44 class.sessioncontroller.php
-rwxrwxr-x 1 arian arian  4205 Feb 16 20:44 class.searchcontroller.php
-rwxrwxr-x 1 arian arian  5104 Feb 16 20:44 class.routescontroller.php
-rw-rw-r-- 1 arian arian   947 Feb 16 20:44 class.rootcontroller.php
-rwxrwxr-x 1 arian arian  8960 Feb 16 20:44 class.rolecontroller.php
-rw-rw-r-- 1 arian arian 58655 Feb 16 20:44 class.profilecontroller.php
-rw-rw-r-- 1 arian arian  3793 Feb 16 20:44 class.notificationscontroller.php
-rw-rw-r-- 1 arian arian  1950 Feb 16 20:44 class.modulecontroller.php
-rwxrwxr-x 1 arian arian  6502 Feb 16 20:44 class.messagecontroller.php
-rw-rw-r-- 1 arian arian 10735 Feb 16 20:44 class.logcontroller.php
-rw-rw-r-- 1 arian arian 10321 Feb 16 20:44 class.importcontroller.php
-rwxrwxr-x 1 arian arian  4118 Feb 16 20:44 class.homecontroller.php
-rwxrwxr-x 1 arian arian  5965 Feb 16 20:44 class.embedcontroller.php
-rw-rw-r-- 1 arian arian  2468 Feb 16 20:44 class.dbacontroller.php
-rwxrwxr-x 1 arian arian  3131 Feb 16 20:44 class.dashboardcontroller.php
-rwxrwxr-x 1 arian arian 62105 Feb 16 20:47 class.entrycontroller.php
```

### PR DESCRIPTION
**Pull request by linc**
Ran `find . -type f -exec chmod -x {} +` on Vanilla to remove executable permissions from all files. Closes #1530

### CODE REVIEW

**Comment by tburry** [comment]
I'm worried that the permissions will just come back when other pull requests are merged. Is that going to happen?

**Comment by linc** [comment]
My understanding is that the executable permission is tracked just like any other code change, and that subsequent merges won't contain a change and therefore will be left alone. The only issue a see down the line is folks accidentally adding new files with +x set unknowingly, but we can keep an eye out for that.

**Comment by linc** [comment]
I've added a commit to set new config.php files to 664 instead of 775 as well.

**Comment by tburry** [comment]
I'd actually rather not do this PR until the casening is done. It's a painful PR and I don't want any chance of it becoming a nightmare.

**Pull request closed without merging**
