### PR TITLE
Fix usage of writeDiscussion()

### PR DESCRIPTION
**Pull request by R-J**
The function writeDiscussion() was called with four parameters, the forth being an alternating class "Alt".
The function only accepts three, so I've deleted those artifacts.

### CODE REVIEW

**Comment by R-J** [comment]
Could anybody stop that @CLAassistant bot? I have signed the agreement before the bot has asked me the first time,[ I've signed it](https://github.com/vanilla/vanilla/pull/3958#issuecomment-218990415) after it has asked me but I really do not want to sign it each time a send a PR.

On my developing machine there I haven't set up a valid mail address, that is correct, but who cares? I have signed it with this GitHub account one time already and shouldn't that be enough?

**Comment by R-J** [comment]
Included in the next PR: https://github.com/vanilla/vanilla/pull/3984

**Comment by hgtonight** [comment]
@R-J Looks like some of your commits aren't using your profile email address (it is using root@localhost).

**Comment by DaazKu** [comment]
@R-J https://github.com/vanilla/vanilla/pull/3987#issuecomment-219774748 Check this comment.

**Comment by R-J** [comment]
I do not like to get too explicit when I write, but that sucks. It really, really sucks a lot. When I first signed  the contributors agreement, it was like signing "don't dry your gerbil in the microwave": do I really have to sign that when I donate code to an open source project, it is no longer my code? Well, I don't mind! It was the first such agreement I ever was even asked to sign and so I was a little bit proud signing that "I will never put any rodent in a washing maschine to clean it".

When the bot asked me, I was excited: what a great idea to cut down bureaucracy! Developers do not have to write Excel lists with names of people who signed the "I will not use my vacuum cleaner for - ehm - *other* purposes" agreement. The  bot simply does so! Great! So I've signed with my GitHub account.

I currently have 4 computers from which I might use git. Sometimes I work as root (bad, I know), sometimes not. So I have to configure it 8 times. And only because that dumb bot cannot accept that  when a pull request from my GitHub account where whoever@localhost contributed, is a pull request from **me**? I've said that before: that sucks.

But hey, a bot is a bot is a bot. So why not click on that link that bot provides in order to get some enlightment? I found something about "open your commit and hover over the question mark". So I open my commit and there is no question mark. Alright. What then? Read the rest, got no clue, found a small link in a red alert box.

Following this link I get a helpfful little script that I have to run, which  needs me to insert the mail I've used. Well, some of my PRs have been done with root@localhost (yes, I know...) and some with r-j@localhost - or has it been rj@localhost? I'm not sure...

Wait, there has been something about less bureaucracy somewhere here, nor? *mumblemumble*sucks*mumblemumble*

What you (you all, not somebody specific but **anybody** who reads this whining) do not know, is that I had a hard struggle with GitHub today. I made a commit and wasn't able to "kill" that. I wanted to create a clean pull request but found no way to do so. Reading GitHub docs showed me a document about "reverting commits": "oh it is so easy just open commit and click revert. You can even revert a revert. We do so the whole day. Revert, revert, revert, revert!" Yeah, but like the question mark, there is also no revert option for me.

It might be my fault but I never ever have used anythingso annoying like GitHub. I managed to do what I needed with command line git. Everything(!) I did today was quite easy with git and finding out how to do so was quite fast, although I'm still a git novice. Using GitHubs documentation was never helpful and always frustrating.

And now there comes the bot, telling me to sign the "Don't clean your teeth with this grinding maschine" agreement. Does it want to beware OS authors from copyright infringement because they are sued by Mr. Root Localhost? I know: he's just a dumb tin head and his existence is helpful for a lot of people, including you (this time you Vanilla guys, which I honestly don't want to blame for what in the end is my fault).

I'm really pissed by GitHub today and I don't feel like creating a script to change what I have done. Maybe tomorrow. Or the day after tomorrow. Not know. I think I'm going to play Borderlands and eat some chocolate to come down now. Have a nice evening everybody (except you, @CLAassistant: go and get yourself a brain!)

P.S.: I know that I could have run that bloody script 10 times instead of writing this novel, but it wouldn't have been so satisfying.

P.P.S.: I hate you, @CLAassistant

**Comment by linc** [comment]
@R-J Having git properly configured is actually pretty important and impacts more things than just the CLA bot. :) I would make it priority to get your machines in sync and pick which email you'd like to be your "canonical" identity. At some point, we may start signing all our code too, and that requires even more careful setup.

The CLA bot also fixes more problems than just automating that agreement. It reduces training required on our side as both our team & pool of contributors expands, it draws a verifiable connection between who is sending code and who is signing the CLA, and it simplifies the process for new contributors by keeping it all on GitHub.

All that said, you don't need to close your PR because the bot returned false. :) I promise we are still smart enough to know it's you and that you signed it. I'd appreciate it if you sorted things out sooner than later, but I'm not gonna start rejecting all your code until then.

It's just a bot. ;)

**Comment by R-J** [comment]
Thanks for the kind words, I've already cooled down. Unfortunately not because of computer games and sugar, but because of 2 hours ironing my shirts...

I haven't closed it because I was in a rage, but because I had those changes also in the next PR. I branched a branch instead of the master and so I had two PRs in one. Luckily they were very closely connected. So I'll close it again :-)

**Pull request closed without merging**
