### PR TITLE
Fix spam logging & log restoring by packing IPs before insertions

### PR DESCRIPTION
**Pull request by topcheese13**
What this PR does
---
We recently updated our handling of IPv6. We found 2 cases where IPs aren't encoded/packed prior to insertion.

We need to encode IPs before inserting them into the Log table to make sure we aren't busting the column limit. This PR does this. We also need to encode IPs before inserting them when restoring from the log, our current process decodes them on fetch. This PR does this.

Strict Mode & IPv6
---
FYI, With our current IP columns set to `VARBINARY 16`, without MySQL strict mode it will actually truncate the value for IPv6, hence, storing a erroneous IP, but with MySQL strict mode it will fail entirely, throwing a `Data too long for column ...` error.

### CODE REVIEW

**Comment by linc** [comment]
Are we in strict mode on cloud?

**Comment by linc** [comment]
This should ideally be referencing an issue it's fixing. At the very least, it should describe the error report we received that it is fixing in the description.

**Comment by dannimajdalani** [comment]
Once a comment is marked as spam, if you flag it as not spam from the dahsboard you'll get the below error:

`Data too long for column 'InsertIPAddress' at row 1|Gdn_ Database|Query|replace `GDN_Comment` (`DiscussionID`, `InsertUserID`, `Body`, `Format`, `DateInserted`, `InsertIPAddress`) values (:DiscussionID, :InsertUserID, :Body, :Format, :DateInserted, :InsertIPAddress)`

**Comment by topcheese13** [comment]
Like I said with strict mode it will fail `Data too long for column ...` without strict mode it won't fail but it will truncate the value, hence, storing a faulty IP address for IPv6.

Regardless of this all of our IPs are stored encoded, not only is it preventing errors and truncating it's also following what we do everywhere else.

**Comment by topcheese13** [comment]
There is nothing wrong with my PR.

It's a result of us storing the IPv6 correctly, it probably gets decoded and never encoded again before restoring it. We need to also encode those IPs before the restore goes through.

**Comment by dannimajdalani** [comment]
And we should create another PR for that?

**Comment by linc** [comment]
Let's get the whole workflow fixed here, please. Update the description of this PR to indicate the scope of the problem we're solving.

Adding a patch and shrugging about MySQL strict mode compliance isn't OK.

**Comment by topcheese13** [comment]
> Let's get the whole workflow fixed here, please. Update the description of this PR to indicate the scope of the problem we're solving.
> 
> Adding a patch and shrugging about MySQL strict mode compliance isn't OK.

I have updated the PR with an extra fix, the title and the description to reflect those changes. MySQL strict mode was just extra information on this PR to explain how this process behaved under strict mode or not, it was never related to the subsequent fix that was needed to restore records. This fix was needed because storing full IPv6 in the log table was than causing the same bug we had on the actual insertion of logs when we were restoring them to their rightful table.

**Pull request merged**
