### PR TITLE
Add HTTP proxy support

### PR DESCRIPTION
**Pull request by mpeltier**
Hi,
Several features of Vanilla do not work if the server is behind an HTTP proxy server. Could you please review this patch which adds the support of an HTTP proxy (with or without cURL). It mainly adds functions in library/core/functions.general.php (is it the right place?) and the following configuration variables:

  $Configuration['Proxy']['Hostname'] = NULL;
  $configuration['Proxy']['Port'] = '3128';
  $Configuration['Proxy']['Login'] = NULL;
  $Configuration['Proxy']['Password'] = NULL;

Other third party plugins not contained in Vanilla core could then use these methods (eg: SocialLogin).

I have made the following tests using Squid. 

Facebook Social Connect = login with facebook whereas a local account exists with the same email
Twitter Social Connect = login with twitter whereas a local account exists with the same email
Google Sign = login with google whereas a local account exists with the same email
OpenID plugin = login with google url whereas a local account exists with the same email

Without proxy and with php-curl extension: 
- Statistics in dashboard: ok
- News feeds in dashboard: ok
- Recaptcha: ok
- Facebook Social Connect: ok
- Twitter Social Connect: ok
- Google Sign In plugin: ok
- OpenID plugin: ok

Without proxy and without php-curl extension:
- Statistics in dashboard: ko (curl is required in library/core/class.proxyrequest.php)
- News feeds in dashboard: ok
- Recaptcha: ok
- Facebook Social Connect: ko (curl is required in plugins/Facebook/class.facebook.plugin.php)
- Twitter Social Connect: ko (curl is required in plugins/Twitter/class.twitter.plugin.php)
- Google Sign In plugin: ok
- OpenID plugin: ok

With proxy and with php-curl extension:
- Statistics in dashboard: ok
- News feeds in dashboard: ok
- Recaptcha: ok
- Facebook Social Connect: ok
- Twitter Social Connect: ok
- Google Sign In plugin: ok
- OpenID plugin: ok

With proxy and without php-curl extension:
- Statistics in dashboard: ko (curl is required in library/core/class.proxyrequest.php)
- News feeds in dashboard: ok
- Recaptcha: ok
- Facebook Social Connect: ko (curl is required in plugins/Facebook/class.facebook.plugin.php)
- Twitter Social Connect: ko (curl is required in plugins/Twitter/class.twitter.plugin.php)
- Google Sign In plugin: ok
- OpenID plugin: ok

With proxy which requires authentication and with php-curl extension:
- Statistics in dashboard: ok
- News feeds in dashboard: ok
- Recaptcha: ok
- Facebook Social Connect: ok
- Twitter Social Connect: ok
- Google Sign In plugin: ok
- OpenID plugin: ok

With proxy which requires authentication and without php-curl extension:
- Statistics in dashboard: ko (curl is required in library/core/class.proxyrequest.php)
- News feeds in dashboard: ok
- Recaptcha: ok
- Facebook Social Connect: ko (curl is required in plugins/Facebook/class.facebook.plugin.php)
- Twitter Social Connect: ko (curl is required in plugins/Twitter/class.twitter.plugin.php)
- Google Sign In plugin: ok
- OpenID plugin: ok

Thanks,
Mathieu

### CODE REVIEW

**Comment by kaecyra** [comment]
Hi there,

Thank you for this pull request. I have a few issues with this that I'd like you to address before I can serious consider this.

1) Instead of adding the $context call before each file_get_contents, I'd rather see a wrapper for file_get_contents that has proxy support. Name the new function "url_get_contents" and give it the same signature as file_get_contents.

2) Create a Proxy.Enabled key, defaulted to false, and depend on that rather than the Hostname, since this allows toggling of the proxy without losing configuration.

3) Use our new naming scheme for functions and boolean/null. Lowercase true/false/null, and functions start with a lowercase letter.

4) Get function names under control. GetStreamContextOptionsForHttpProxy is kind of a monster. Perhaps "proxyStreamContext". I'd also get rid of the SetHttpProxyForCurl and rather just make it a static method on ProxyRequest. Call it something like applyProxy()

5) Merge our latest master into your PR so that it can be auto-merged.

Thanks again

**Comment by mpeltier** [comment]
Thanks for the reply. I will try to address these isssues and will get back to you.
Mathieu

**Comment by tburry** [comment]
Adding to #5 from @kaecyra. It might be easier to rebase your branch onto our current master and open up a new PR from that since we've been doing quite a bit of merging ourselves. We are also planning to do a big master merge tomorrow so you might want to hold off on that.

**Comment by linc** [comment]
@mpeltier The merge is done! Going to close this to make way for a new one if you're inclined to revisit this. Thanks for your patience!

**Pull request closed without merging**
