### PR TITLE
Create foundation theme package

### PR DESCRIPTION
**Pull request by charrondev**
Closes https://github.com/vanilla/vanilla/issues/9903

- Much of boilerplate moved out to packages/theme-core
- Foundation and keystone moved to new directory.
- Keystone & Foundation now depends on theme-core instead of boilerplate

## Theme scaffolding script

Run `yarn scaffold theme`. It will tell you what parameters you need.

image

image

### CODE REVIEW

**Comment by cchabilall83** [comment]
@charrondev  I tried to scaffold out a new theme but when I restarted my build I get the following error

[20-Jan-2020 16:41:38 UTC] PHP Warning:  Multiple exceptions encountered while dispatching . in /srv/vanilla-repositories/vanilla/library/core/class.dispatcher.php on line 878

**Comment by charrondev** [comment]
@cchabilall83 Should be fixed. Try and create the theme again.

**Comment by cchabilall83** [comment]
It's working now.

Tested applying keystone, boilerplate and foundation.  Everything seems to work.

**Comment by charrondev** [comment]
@igraziatto Both issues should be resolved now. I added a new build troubleshooting into the README and script that runs before the build to check for some common issues.

**Pull request merged**
