### PR TITLE
Fixed List styles in userContent

### PR DESCRIPTION
**Pull request by slafleche**
Closes: https://github.com/vanilla/vanilla/issues/8985

Note: The styles were broken on the KB side. The legacy styles (forum) were working fine. 

I also added different bullets for multi level lists, as per https://github.com/vanilla/vanilla/issues/8985

Companion PR: https://github.com/vanilla/knowledge/pull/1141

### CODE REVIEW

**Comment by charrondev** [comment]
While we're in doing this could we fix up the margins on the nested items?

|Actual|Mockups|
|---|---|
|image|image|

**Comment by slafleche** [comment]
List margins have been reviewed by @ElisaAlmeida

**Comment by charrondev** [comment]
https://github.com/vanilla/vanilla/pull/9174/commits/6744d2b2d6a5cd0f2b59a146c9f9f59d933694e4#diff-f36d959f0fbe0802d83acd2ecf5d101cR175-R180

Because these are missing `&` they end up applying to everything. It messed up some of our list margins all over the place.

image

**Comment by slafleche** [comment]
Fixed the selectors... still getting that error through @charrondev

**Pull request merged**
