### PR TITLE
Verify unconfirmed roles before attempting to update them

### PR DESCRIPTION
**Pull request by initvector**
Attempt, the second, after needing to revisit following https://github.com/vanilla/vanilla/pull/4303

### CODE REVIEW

**Comment by initvector** [comment]
Need to tweak this, just a bit, to add similar handling for the other couple of configs like this above it.

**Comment by initvector** [comment]
I've expanded the fix to include converting roles from `Garden.Registration.ApplicantRoleID` and
`Garden.Registration.DefaultRoles`, in addition to `Garden.Registration.ConfirmEmailRole`

**Comment by initvector** [comment]
I simplified the routine a little more.  This was possible by removing the legacy role config data from config-defaults.php.

**Comment by linc** [comment]
This looks good to me.

**Pull request merged**
