### PR TITLE
Fix use of MAX_SIGNED_INT constant

### PR DESCRIPTION
**Pull request by bleistivt**
class constants need to be accessed with self:: inside of the class

### CODE REVIEW

**Comment by bleistivt** [comment]
Also, shouldn't this be a Gdn_UserException?

**Comment by linc** [comment]
Let us never speak of this again. ;) lol (Nice save).

**Comment by linc** [comment]
To be honest, I'm a little murky on exception differentiation. This is a fairly critical and non-user-facing exception in all likelihood, so I went with a straight Exception.

**Comment by bleistivt** [comment]
You can thank me for living dangerously on master :D
 I'm usually like "looks safe" and pull from master to my site. But once in a while -> dramatic trainwreck

**Pull request merged**
