### PR TITLE
Make HTML in categories description consistent

### PR DESCRIPTION
**Pull request by bleistivt**
new PR for #2435

### CODE REVIEW

**Comment by linc** [comment]
@beckyvb What's the theme implications here for clients? Is this a relatively safe change?

**Comment by beckyvb** [comment]
This seems like a safe change, and it's completely sane to want to standardize the way we output the category description between the two views. While we're at it though, I'd recommend calling Gdn_Format::htmlFilter on the category description data before outputting.

**Comment by linc** [comment]
@bleistivt up for adding a quick `htmlFilter()`? Thanks!

**Comment by bleistivt** [comment]
Done!

**Pull request merged**
