### PR TITLE
Optimize images for shrinkray-1

### PR DESCRIPTION
**Pull request by tburry**

### CODE REVIEW

**Comment by tburry** [comment]
Images shrunk 0.11% (1987b -> 1985b)


* resources/emoji/anguished.png (1987b -> 1985b)

**Comment by tburry** [comment]
Images shrunk 8.03% (4994b -> 4593b)


* resources/emoji/cry.png (2013b -> 2012b)
* resources/emoji/frowning.png (2981b -> 2581b)

**Comment by tburry** [comment]
Images shrunk 35.18% (47290b -> 30657b)


* resources/emoji/icon.png (47290b -> 30657b)

**Comment by tburry** [comment]
Images shrunk 3.36% (8714b -> 8422b)


* resources/emoji/triumph.png (2028b -> 2027b)
* resources/emoji/unamused.png (2005b -> 2004b)
* resources/emoji/wink.png (2011b -> 2010b)
* resources/emoji/worried.png (2670b -> 2381b)

**Comment by tburry** [comment]
Images shrunk 0.48% (3781b -> 3763b)


* applications/dashboard/design/images/usericon.png (3781b -> 3763b)

**Comment by tburry** [comment]
Images shrunk 15.85% (486b -> 409b)


* plugins/EmojiExtender/emoji/little/+1.png (486b -> 409b)

**Comment by tburry** [comment]
Images shrunk 21.58% (7744b -> 6073b)


* plugins/EmojiExtender/emoji/little/-1.png (493b -> 408b)
* plugins/EmojiExtender/emoji/little/angry.png (714b -> 489b)
* plugins/EmojiExtender/emoji/little/anguished.png (756b -> 604b)
* plugins/EmojiExtender/emoji/little/awesome.png (603b -> 542b)
* plugins/EmojiExtender/emoji/little/bawling.png (1179b -> 1046b)
* plugins/EmojiExtender/emoji/little/blush.png (812b -> 627b)
* plugins/EmojiExtender/emoji/little/chuffed.png (760b -> 569b)
* plugins/EmojiExtender/emoji/little/confounded.png (800b -> 573b)
* plugins/EmojiExtender/emoji/little/confused.png (747b -> 541b)
* plugins/EmojiExtender/emoji/little/cry.png (880b -> 674b)

**Comment by tburry** [comment]
Images shrunk 24.03% (7788b -> 5917b)


* plugins/EmojiExtender/emoji/little/dizzy.png (870b -> 664b)
* plugins/EmojiExtender/emoji/little/eh.png (833b -> 599b)
* plugins/EmojiExtender/emoji/little/expressionless.png (604b -> 419b)
* plugins/EmojiExtender/emoji/little/fearful.png (737b -> 489b)
* plugins/EmojiExtender/emoji/little/frown.png (731b -> 569b)
* plugins/EmojiExtender/emoji/little/glasses.png (806b -> 641b)
* plugins/EmojiExtender/emoji/little/grin.png (767b -> 590b)
* plugins/EmojiExtender/emoji/little/heart.png (700b -> 588b)
* plugins/EmojiExtender/emoji/little/heartbreak.png (888b -> 751b)
* plugins/EmojiExtender/emoji/little/hurrah.png (852b -> 607b)

**Comment by tburry** [comment]
Images shrunk 21.04% (7919b -> 6253b)


* plugins/EmojiExtender/emoji/little/innocent.png (904b -> 679b)
* plugins/EmojiExtender/emoji/little/lol.png (824b -> 659b)
* plugins/EmojiExtender/emoji/little/love.png (749b -> 635b)
* plugins/EmojiExtender/emoji/little/mrgreen.png (643b -> 489b)
* plugins/EmojiExtender/emoji/little/naughty.png (876b -> 736b)
* plugins/EmojiExtender/emoji/little/neutral.png (697b -> 473b)
* plugins/EmojiExtender/emoji/little/pleased.png (772b -> 605b)
* plugins/EmojiExtender/emoji/little/proud.png (764b -> 593b)
* plugins/EmojiExtender/emoji/little/rage.png (878b -> 728b)
* plugins/EmojiExtender/emoji/little/scream.png (812b -> 656b)

**Comment by tburry** [comment]
Images shrunk 22.32% (7520b -> 5842b)


* plugins/EmojiExtender/emoji/little/silenced.png (797b -> 563b)
* plugins/EmojiExtender/emoji/little/skull.png (715b -> 662b)
* plugins/EmojiExtender/emoji/little/smile.png (711b -> 488b)
* plugins/EmojiExtender/emoji/little/smiley.png (649b -> 471b)
* plugins/EmojiExtender/emoji/little/star.png (553b -> 478b)
* plugins/EmojiExtender/emoji/little/sunglasses.png (794b -> 621b)
* plugins/EmojiExtender/emoji/little/surprised.png (778b -> 601b)
* plugins/EmojiExtender/emoji/little/sweat.png (886b -> 707b)
* plugins/EmojiExtender/emoji/little/tongue.png (830b -> 664b)
* plugins/EmojiExtender/emoji/little/unamused.png (807b -> 587b)

**Comment by tburry** [comment]
Images shrunk 70.82% (17552b -> 5123b)


* plugins/EmojiExtender/emoji/rice/dizzy.png (4178b -> 486b)
* plugins/EmojiExtender/emoji/rice/eh.png (4129b -> 466b)
* plugins/EmojiExtender/emoji/rice/fearful.png (786b -> 648b)
* plugins/EmojiExtender/emoji/rice/frown.png (655b -> 446b)
* plugins/EmojiExtender/emoji/rice/glasses.png (765b -> 462b)
* plugins/EmojiExtender/emoji/rice/innocent.png (1306b -> 727b)
* plugins/EmojiExtender/emoji/rice/kiss.png (735b -> 478b)
* plugins/EmojiExtender/emoji/rice/lol.png (754b -> 667b)
* plugins/EmojiExtender/emoji/rice/love.png (4244b -> 743b)

**Comment by tburry** [comment]
Images shrunk 41.91% (11434b -> 6643b)


* plugins/EmojiExtender/emoji/little/waving.png (817b -> 608b)
* plugins/EmojiExtender/emoji/little/wink.png (740b -> 534b)
* plugins/EmojiExtender/emoji/little/winky.png (684b -> 576b)
* plugins/EmojiExtender/emoji/rice/+1.png (669b -> 421b)
* plugins/EmojiExtender/emoji/rice/-1.png (4067b -> 427b)
* plugins/EmojiExtender/emoji/rice/angry.png (1394b -> 1357b)
* plugins/EmojiExtender/emoji/rice/blush.png (720b -> 654b)
* plugins/EmojiExtender/emoji/rice/chuffed.png (769b -> 661b)
* plugins/EmojiExtender/emoji/rice/crazy.png (852b -> 747b)
* plugins/EmojiExtender/emoji/rice/cry.png (722b -> 658b)

**Comment by tburry** [comment]
Images shrunk 68.71% (11812b -> 3697b)


* plugins/EmojiExtender/emoji/rice/smile.png (700b -> 463b)
* plugins/EmojiExtender/emoji/rice/sunglasses.png (4166b -> 473b)
* plugins/EmojiExtender/emoji/rice/sweat.png (786b -> 729b)
* plugins/EmojiExtender/emoji/rice/tongue.png (703b -> 653b)
* plugins/EmojiExtender/emoji/rice/unamused.png (4088b -> 458b)
* plugins/EmojiExtender/emoji/rice/wink.png (688b -> 465b)
* plugins/EmojiExtender/emoji/rice/yum.png (681b -> 456b)

**Comment by tburry** [comment]
Images shrunk 65.11% (18317b -> 6392b)


* plugins/EmojiExtender/emoji/rice/money.png (777b -> 686b)
* plugins/EmojiExtender/emoji/rice/naughty.png (889b -> 755b)
* plugins/EmojiExtender/emoji/rice/neutral.png (701b -> 461b)
* plugins/EmojiExtender/emoji/rice/ohnoes.png (816b -> 653b)
* plugins/EmojiExtender/emoji/rice/pirate.png (918b -> 786b)
* plugins/EmojiExtender/emoji/rice/rage.png (4195b -> 642b)
* plugins/EmojiExtender/emoji/rice/sarcastic.png (799b -> 493b)
* plugins/EmojiExtender/emoji/rice/scream.png (4133b -> 647b)
* plugins/EmojiExtender/emoji/rice/sick.png (4355b -> 789b)
* plugins/EmojiExtender/emoji/rice/silenced.png (734b -> 480b)

**Comment by tburry** [comment]
Images shrunk 41.17% (1533b -> 902b)


* plugins/EmojiExtender/emoji/twitter/mrgreen.png (1533b -> 902b)

**Comment by tburry** [comment]
Images shrunk 48.44% (1053b -> 543b)


* plugins/EmojiExtender/emoji/twitter/smile.png (1053b -> 543b)

**Comment by kaecyra** [comment]
You're mad with power!

**Comment by tburry** [comment]
Images shrunk 4.9% (11077b -> 10535b)


* plugins/EmojiExtender/icon.png (9440b -> 8916b)
* plugins/Facebook/icon.png (1637b -> 1619b)

**Comment by tburry** [comment]
Images shrunk 3.46% (53383b -> 51539b)


* plugins/GooglePlus/icon.png (7641b -> 7539b)
* plugins/GooglePrettify/icon.png (3763b -> 3700b)
* plugins/Gravatar/icon.png (4886b -> 4605b)
* plugins/OpenID/icon.png (8970b -> 8405b)
* plugins/StopForumSpam/icon.png (6135b -> 6089b)
* plugins/editor/icon.png (19037b -> 18289b)
* plugins/vanillicon/icon.png (2951b -> 2912b)

**Comment by kaecyra** [comment]
Oh god when will it end

**Comment by tburry** [comment]
Images shrunk 36.15% (19328b -> 12342b)


* plugins/EmojiExtender/emoji/little/cry@2x.png (2292b -> 1508b)
* plugins/EmojiExtender/emoji/little/dizzy@2x.png (2359b -> 1548b)
* plugins/EmojiExtender/emoji/little/eh@2x.png (2258b -> 1262b)
* plugins/EmojiExtender/emoji/little/expressionless@2x.png (1419b -> 749b)
* plugins/EmojiExtender/emoji/little/fearful@2x.png (1699b -> 941b)
* plugins/EmojiExtender/emoji/little/frown@2x.png (1824b -> 1112b)
* plugins/EmojiExtender/emoji/little/glasses@2x.png (1900b -> 1332b)
* plugins/EmojiExtender/emoji/little/grin@2x.png (1863b -> 1212b)
* plugins/EmojiExtender/emoji/little/heart@2x.png (1554b -> 1156b)
* plugins/EmojiExtender/emoji/little/heartbreak@2x.png (2160b -> 1522b)

**Comment by tburry** [comment]
Images shrunk 35.16% (44190b -> 28653b)


* plugins/EmojiExtender/emoji/little/hurrah@2x.png (2128b -> 1284b)
* plugins/EmojiExtender/emoji/little/innocent@2x.png (2262b -> 1497b)
* plugins/EmojiExtender/emoji/little/little-icon.png (27679b -> 17989b)
* plugins/EmojiExtender/emoji/little/lol@2x.png (2146b -> 1447b)
* plugins/EmojiExtender/emoji/little/love@2x.png (2007b -> 1477b)
* plugins/EmojiExtender/emoji/little/mrgreen@2x.png (1586b -> 1081b)
* plugins/EmojiExtender/emoji/little/naughty@2x.png (2320b -> 1648b)
* plugins/EmojiExtender/emoji/little/neutral@2x.png (1742b -> 917b)
* plugins/EmojiExtender/emoji/little/no_mouth.png (670b -> 441b)
* plugins/EmojiExtender/emoji/little/no_mouth@2x.png (1650b -> 872b)

**Comment by tburry** [comment]
Images shrunk 32.37% (17534b -> 11859b)


* plugins/EmojiExtender/emoji/little/open_mouth.png (737b -> 576b)
* plugins/EmojiExtender/emoji/little/open_mouth@2x.png (1817b -> 1196b)
* plugins/EmojiExtender/emoji/little/pleased@2x.png (1979b -> 1210b)
* plugins/EmojiExtender/emoji/little/proud@2x.png (1864b -> 1254b)
* plugins/EmojiExtender/emoji/little/rage@2x.png (2203b -> 1741b)
* plugins/EmojiExtender/emoji/little/scream@2x.png (2006b -> 1384b)
* plugins/EmojiExtender/emoji/little/silenced@2x.png (1912b -> 1194b)
* plugins/EmojiExtender/emoji/little/skull@2x.png (1713b -> 1382b)
* plugins/EmojiExtender/emoji/little/smile@2x.png (1790b -> 973b)
* plugins/EmojiExtender/emoji/little/smiley@2x.png (1513b -> 949b)

**Comment by tburry** [comment]
Images shrunk 34.09% (18158b -> 11968b)


* plugins/EmojiExtender/emoji/little/angry@2x.png (1656b -> 976b)
* plugins/EmojiExtender/emoji/little/anguished@2x.png (1942b -> 1299b)
* plugins/EmojiExtender/emoji/little/awesome@2x.png (1487b -> 1170b)
* plugins/EmojiExtender/emoji/little/bawling@2x.png (2949b -> 2324b)
* plugins/EmojiExtender/emoji/little/bleep_bloop.png (679b -> 553b)
* plugins/EmojiExtender/emoji/little/bleep_bloop@2x.png (1426b -> 939b)
* plugins/EmojiExtender/emoji/little/blush@2x.png (2145b -> 1360b)
* plugins/EmojiExtender/emoji/little/chuffed@2x.png (1998b -> 1132b)
* plugins/EmojiExtender/emoji/little/confounded@2x.png (1988b -> 1108b)
* plugins/EmojiExtender/emoji/little/confused@2x.png (1888b -> 1107b)

**Comment by tburry** [comment]
Images shrunk 29.71% (2185b -> 1536b)


* plugins/EmojiExtender/emoji/little/+1@2x.png (1077b -> 768b)
* plugins/EmojiExtender/emoji/little/-1@2x.png (1108b -> 768b)

**Comment by tburry** [comment]
Images shrunk 40.34% (21949b -> 13095b)


* plugins/EmojiExtender/emoji/little/star@2x.png (1178b -> 957b)
* plugins/EmojiExtender/emoji/little/sunglasses@2x.png (1933b -> 1370b)
* plugins/EmojiExtender/emoji/little/surprised@2x.png (1960b -> 1257b)
* plugins/EmojiExtender/emoji/little/sweat@2x.png (2355b -> 1523b)
* plugins/EmojiExtender/emoji/little/tongue@2x.png (2216b -> 1427b)
* plugins/EmojiExtender/emoji/little/unamused@2x.png (2049b -> 1165b)
* plugins/EmojiExtender/emoji/little/waving@2x.png (2107b -> 1270b)
* plugins/EmojiExtender/emoji/little/wink@2x.png (1846b -> 1045b)
* plugins/EmojiExtender/emoji/little/winky@2x.png (1614b -> 1233b)
* plugins/EmojiExtender/emoji/none/none-icon.png (4691b -> 1848b)

**Comment by tburry** [comment]
Images shrunk 14.2% (18130b -> 15556b)


* plugins/EmojiExtender/emoji/rice/+1@2x.png (1435b -> 1311b)
* plugins/EmojiExtender/emoji/rice/-1@2x.png (1450b -> 1314b)
* plugins/EmojiExtender/emoji/rice/angry@2x.png (1896b -> 1638b)
* plugins/EmojiExtender/emoji/rice/blush@2x.png (1700b -> 1523b)
* plugins/EmojiExtender/emoji/rice/chuffed@2x.png (1769b -> 1505b)
* plugins/EmojiExtender/emoji/rice/crazy@2x.png (2110b -> 1902b)
* plugins/EmojiExtender/emoji/rice/cry@2x.png (2011b -> 1766b)
* plugins/EmojiExtender/emoji/rice/dizzy@2x.png (1948b -> 1211b)
* plugins/EmojiExtender/emoji/rice/eh@2x.png (1858b -> 1668b)
* plugins/EmojiExtender/emoji/rice/fearful@2x.png (1953b -> 1718b)

**Comment by tburry** [comment]
Images shrunk 18.19% (19586b -> 16024b)


* plugins/EmojiExtender/emoji/rice/frown@2x.png (1460b -> 1277b)
* plugins/EmojiExtender/emoji/rice/glasses@2x.png (2074b -> 1283b)
* plugins/EmojiExtender/emoji/rice/innocent@2x.png (2756b -> 1754b)
* plugins/EmojiExtender/emoji/rice/kiss@2x.png (1733b -> 1517b)
* plugins/EmojiExtender/emoji/rice/lol@2x.png (1865b -> 1628b)
* plugins/EmojiExtender/emoji/rice/love@2x.png (2121b -> 1882b)
* plugins/EmojiExtender/emoji/rice/money@2x.png (1929b -> 1793b)
* plugins/EmojiExtender/emoji/rice/naughty@2x.png (2196b -> 1927b)
* plugins/EmojiExtender/emoji/rice/neutral@2x.png (1570b -> 1317b)
* plugins/EmojiExtender/emoji/rice/ohnoes@2x.png (1882b -> 1646b)

**Comment by tburry** [comment]
Images shrunk 17.35% (38678b -> 31970b)


* plugins/EmojiExtender/emoji/rice/pirate@2x.png (2711b -> 2602b)
* plugins/EmojiExtender/emoji/rice/rage@2x.png (2369b -> 2047b)
* plugins/EmojiExtender/emoji/rice/rice-icon.png (19643b -> 15517b)
* plugins/EmojiExtender/emoji/rice/sarcastic@2x.png (1957b -> 1720b)
* plugins/EmojiExtender/emoji/rice/scream@2x.png (1941b -> 1671b)
* plugins/EmojiExtender/emoji/rice/sick@2x.png (2756b -> 2496b)
* plugins/EmojiExtender/emoji/rice/silenced@2x.png (1742b -> 1568b)
* plugins/EmojiExtender/emoji/rice/smile@2x.png (1680b -> 1416b)
* plugins/EmojiExtender/emoji/rice/sunglasses@2x.png (2024b -> 1272b)
* plugins/EmojiExtender/emoji/rice/sweat@2x.png (1855b -> 1661b)

**Comment by kaecyra** [comment]
Jesus christ, the humanity!

**Comment by tburry** [comment]
Images shrunk 19.0% (6716b -> 5440b)


* plugins/EmojiExtender/emoji/rice/tongue@2x.png (1680b -> 1502b)
* plugins/EmojiExtender/emoji/rice/unamused@2x.png (1678b -> 1424b)
* plugins/EmojiExtender/emoji/rice/wink@2x.png (1636b -> 1453b)
* plugins/EmojiExtender/emoji/rice/yum@2x.png (1722b -> 1061b)

**Comment by tburry** [comment]
Images shrunk 45.82% (27130b -> 14701b)


* plugins/EmojiExtender/emoji/twitter/twitter-icon.png (16505b -> 8187b)
* plugins/EmojiExtender/emoji/yahoo/yahoo-icon.png (10625b -> 6514b)

**Comment by tburry** [comment]
Images shrunk 7.95% (83790b -> 77137b)


* plugins/editor/icon-template-798x798.png (83790b -> 77137b)

**Comment by kaecyra** [comment]
Is it safe to come out yet?

Is it safe?

**Pull request merged**
