### PR TITLE
Display meta description and image for comment permalinks

### LINKED ISSUE #6278: Comment links should preview the comment, not the OP
Our OpenGraph data should be specific to a linked comment. 

This is wrong (example from HipChat):
screen shot 2017-12-25 at 9 48 19 am

It should keep the title, but excerpt the comment linked, not the discussion.

### LINKED ISSUE #9373: Rich Editor: Linking to a Vanilla comment previews first comment in page instead of the one linked
When linking directly to a comment in Vanilla, the preview description is selected from the first comment on the page rather than the one linked. It would make the intention much clearer to quote the correct comment.

### PR DESCRIPTION
**Pull request by bleistivt**
partially fixes #9373
fixes #6278

### CODE REVIEW

**Comment by charrondev** [comment]
Sorry, this has the same issue with the CI setup. I'll get it resolved next wednesday,

**Comment by bleistivt** [comment]
I pretty much just reshuffled what was already there. But I just went ahead and removed all uppercase variable names and references to Gdn_Format I could. Note that pageNumber needs to be cast to an int as it actually returns a float (1.0).

How to test:
Paste into a tweet/slack message etc.:

* a regular discussion link
* a discussion link that contains a page number
* a comment permalink

The content should be different in all 3.

**Comment by bleistivt** [comment]
I resolved the conflict. Is there something else that should be changed?

**Comment by bleistivt** [comment]
I will close this pull request. Apparently comment shareability is not seen as a pressing issue, even though this feature has been requested by actual users mutliple times.

I will also not even try to contribute to this project anymore as long as the stale bot remains active.
Some info on why it should be considered harmful: https://blog.benwinding.com/github-stale-bots/

For users with the same issue:
**If you want to have embeds (e.g. twitter cards) that are actually useful when a comment is permalinked, add this to a plugin:**

```
    public function discussionController_render_before($sender) {
        if (isset($this->commentID)) {
            $formatService = Gdn::formatService();

            $linkComment = Gdn_DataSet::index($sender->Data['Comments'], 'CommentID')[$this->commentID];
            $sender->description(sliceParagraph($formatService->renderPlainText($linkComment->Body, $linkComment->Format), 160));

            $dom = pQuery::parseStr($formatService->renderHTML($linkComment->Body, $linkComment->Format));
            $sender->setData('_Images', []);
            foreach ($dom->query('img') as $img) {
                if ($img->attr('src')) {
                    $sender->image($img->attr('src'));
                }
            }
        }
    }


    public function discussionController_initialize_handler($sender) {
        if (stringBeginsWith($sender->SelfUrl, 'discussion/comment/')) {
            $this->commentID = stringBeginsWith($sender->SelfUrl, 'discussion/comment/', true, true);
        }
    }
```

**Comment by tburry** [comment]
I understand your frustration in not having your PR merged. Understand though that it's difficult to merge pull requests with no test coverage. It means that we have to find someone to test the PR and figure out if it's okay. Maybe fork it and add our own tests. We've gone through this before where we've merged a PR that seemed just fine, but it's had wide-reaching consequences on a bunch of sites. Once we merge a PR it becomes our responsibility to support.

**Pull request closed without merging**
