### PR TITLE
Hide email preferences when email is disabled

### LINKED ISSUE #2074: Garden.Email.Disabled should make email and email options not appear in ui
Config Settings

                'Preferences.Email.ConversationMessage' => false,
                'Preferences.Email.BookmarkComment' => false,
                'Preferences.Email.ParticipateComment' => false,
                'Preferences.Email.WallComment' => false,
                'Preferences.Email.ActivityComment' => false,
                'Preferences.Email.DiscussionComment' => false,
                'Preferences.Email.Mention' => false,
                'Preferences.Email.Groups' => false,
                'Preferences.Email.Events' => false,

### PR DESCRIPTION
**Pull request by linc**
Closes #2074

I acknowledge this adds logic to a view, but submit that those views need a massive refactor and this does not significantly increase the scope of that effort.

### CODE REVIEW

**Comment by DaazKu** [comment]
Hahahahaha. I had to revert that exact same change a while back XD

https://github.com/vanilla/vanilla/pull/4140/commits/ce7e6db9e19622f2460bccbb5997bb9096cf5f1c

**Comment by linc** [comment]
Well you didn't revisit it!

**Comment by linc** [comment]
It's also a fair point that I *did* do it without adding as much logic to the view by cheating with a CSS class.

**Comment by DaazKu** [comment]
It is all well and good. I just found that funny.

**Pull request merged**
