### PR TITLE
Add Recaptcha localization & standardize calls to Captcha

### PR DESCRIPTION
**Pull request by linc**
See https://github.com/vanilla/vanilla/pull/1796 for details & conversation. This simply re-targets against stage.

### CODE REVIEW

**Comment by linc** [comment]
@beckyvb @MightyCoder Either of you interested in implementing Todd's feedback on this one to finish it? It looks like a straightforward chance to play in the Locale class and write some new code.

Supported languages list moved to here: https://developers.google.com/recaptcha/docs/language

**Comment by linc** [comment]
They don't want RecaptchaOptions as a proper JSON-encoded array. The options are variables so they can't be quoted. Referencing here: https://developers.google.com/recaptcha/old/docs/customization

I've implemented `Gdn::Locale()->Language()` and the Google whitelist & `lang` parameter in my latest commit.

**Comment by tburry** [comment]
Are you sure about that? I don't think javascript even works like that.

**Comment by tburry** [comment]
@linc, pinging you on my last comment. Javascript objects are javascript objects and can accept quoted keys.

**Comment by linc** [comment]
Yup, this is still on my todo list this month.

**Comment by initvector** [comment]
Fixed a typo in Gdn_Locale::Language and switched up RecaptchaOptions to be stored as a PHP array, but sent as JSON.

**Pull request merged**
