### PR TITLE
Add support for mentions in brackets

### PR DESCRIPTION
**Pull request by R-J**
`(@someone)` wasn't recognized as a mention. Changed regex to allow that,

### CODE REVIEW

**Comment by linc** [comment]
Looks good.

**Comment by bleistivt** [comment]
Shouldn't this be `\(` ?

**Comment by linc** [comment]
That's what he added. Can you elaborate?

**Comment by bleistivt** [comment]
This adds a closing bracket which allows for )@mention but not (@mention which I think was the intention.

**Comment by linc** [comment]
Looks like @R-J and I have complimentary cases of dyslexia.

**Pull request merged**
