### PR TITLE
Move the swagger plugin to core as swagger-ui

### PR DESCRIPTION
**Pull request by tburry**
Swagger will now be a core part of Vanilla. This move has a few changes:

- The API portion of the plugin is now core.
- The javascript is now included in the view rather than a separate
event.
- Some CSS tweaks that were removed earlier were added back in.
- The addon is enabled by default and hidden now.

### CODE REVIEW

**Comment by tburry** [comment]
Closes #6046.

**Comment by charrondev** [comment]
It seems this doesn't have the fixes from https://github.com/vanilla/internal/pull/1488. I discovered a potential security issue there and resolved it.

**Comment by tburry** [comment]
@charrondev I copied your changes in.

**Comment by charrondev** [comment]
My only question here is why are we including the JS in a view instead of just adding a deferred JS file through the controller? I see why we don't want to use and event here, but just adding it to head deferred would accomplish the same thing.

**Pull request merged**
