### PR TITLE
Delete all UserConversation entries when delete a user's content

### PR DESCRIPTION
**Pull request by DaazKu**
Fix https://github.com/vanilla/vanilla/issues/5258

Clean UserConversation and ConversationMessage properly

### CODE REVIEW

**Comment by linc** [comment]
nfl-ref-meeting-after-reviewing-the-play-the-call-on-the-field-stands-no-danglers

**Comment by initvector** [comment]
Won't this potentially delete `UserConversation` and `ConversationMessage` records for every conversation the user participated in, now that we're targeting based on `Conversation.UpdateUserID`? If the user was the last poster in a group conversation, every other person in that conversation might lose access when the user is deleted.

The original issue also mentions a concern about replaying conversation/message IDs.

> If their conversations were ALSO the most recent, that means the indices can reset in MySQL. It then will replay those conversationIDs, and those recipients will appear as "random" additions to newly created private messages.

Is that something can be addressed here?

**Comment by DaazKu** [comment]
> Won't this potentially delete UserConversation and ConversationMessage records for every conversation the user participated in, now that we're targeting based on Conversation.UpdateUserID? If the user was the last poster in a group conversation, every other person in that conversation might lose access when the user is deleted.

Nothing changed here. I'm just cleaning the UserConversation and ConversationMessage tables properly.
Now if we want to change the behaviour that's another thing!

> If their conversations were ALSO the most recent, that means the indices can reset in MySQL. It then will replay those conversationIDs, and those recipients will appear as "random" additions to newly created private messages.

Not an issue with the current fix since the records are properly cleaned.

**Comment by initvector** [comment]
> Nothing changed here. I'm just cleaning the UserConversation and ConversationMessage tables properly.
Now if we want to change the behaviour that's another thing!

Very true! The thing I was worried about is actually existing behavior, introduced in the time before time.

**Pull request merged**
