### PR TITLE
Rename column DateExpire to DateExpires

### PR DESCRIPTION
**Pull request by DaazKu**
The column was not named properly.

### CODE REVIEW

**Comment by R-J** [comment]
Seems as if this needs to be backported to 2.5: https://open.vanillaforums.com/discussion/35688/invalid-default-value-for-dateexpires-vanilla-2-5#latest

**Comment by linc** [comment]
I've forcibly backported this to the `release/2.5` branch.

**Comment by brucep** [comment]
@R-J I just had the same issue on 2.5.1.

**Comment by R-J** [comment]
@brucep Your error is connected to this, but not the same. Your problem is discussed [here](https://github.com/vanilla/vanilla/issues/5832)

**Pull request merged**
