### PR TITLE
Fix $Database definition in conversations/structure

### PR DESCRIPTION
**Pull request by R-J**
The variable definition was missing.

### CODE REVIEW

**Comment by tburry** [comment]
These are all variables that are defined before inclusion.

**Comment by R-J** [comment]
I haven't noticed that.

I was debugging a problem with utility/structure and saw that I'm able to run it for specific applications only: `public function structure($appName = 'all')`. So I've tried /utility/structure/vanilla,  /utility/structure/conversations and both failed.

So either the method structure() shouldn't offer the use of an argument or using the arguments shouldn't fail.

**Comment by hgtonight** [comment]
Seems like the specific `$appName` functionality should be scrapped or expanded to include plugins. All plugins' structures are executed every structure call, regardless of the "specific" app.

**Comment by tburry** [comment]
We will be scrapping the $appName functionality. I think that's already in PR.

**Pull request closed without merging**
