### PR TITLE
Harmonize charset (where used) in htmlspecialchars

### PR DESCRIPTION
**Pull request by R-J**
htmlspecialchars uses a mixture of `C('Garden.Charset', '')`, `C('Garden.Charset', 'UTF-8')`, `UTF-8` and no charset info at all. I've harmonized all that uses any charset parameter to respect config setting and default to UTF-8 (`C('Garden.Charset', 'UTF-8')`)

### CODE REVIEW

**Comment by bleistivt** [comment]
+1

@tburry For the future, what do you think about adding a wrapper function for htmlspecialchars like ``hsc()`` or just ``h()``?
I've seen this in a lot of frameworks, it saves typing and gives a chance to define a charset globally.

**Comment by linc** [comment]
Looks good to me.

I am going to cautiously +1 the wrapper idea because we use `htmlspecialchars` in more than 150 places in core and clearly it's gotten out of whack.

**Comment by linc** [comment]
@tburry thoughts?

**Comment by tburry** [comment]
I'm up for the wrapper. List some options.

```
hsc()
h() // nope
hesc() // for html escape, html special chars is such a phpism.
```

**Comment by linc** [comment]
I think I'd like `htmlEsc()` for clarity. I'm not a fan of abbreviating into obfuscation, and this isn't nearly at the level of `c()` or `t()` usage.

**Pull request merged**
