### PR TITLE
Update styles of Tiles components to reflect mockups when 2,3,4 columns

### PR DESCRIPTION
**Pull request by alex-mtl**
Relates to: https://github.com/vanilla/knowledge/issues/1468

### CODE REVIEW

**Comment by charrondev** [comment]
@alex-mtl when I look at the story https://www.chromaticqa.com/snapshot?appId=5d5eba16c782b600204ba187&id=5e1cdde785e3fb0020bb023f I only ever see 2 columns even though it looks like there are supposed to be 3 and 4 columns variants.

**Comment by alex-mtl** [comment]
@charrondev 
> @alex-mtl when I look at the story https://www.chromaticqa.com/snapshot?appId=5d5eba16c782b600204ba187&id=5e1cdde785e3fb0020bb023f I only ever see 2 columns even though it looks like there are supposed to be 3 and 4 columns variants.

If you check real storybook page you will see 3 and 4 columns. According to @slafleche the layout should stay flexible and responsive. That means that visually depending of the media width it could look "2 columns" the design styles and component are rendered as 3 or 4.

**Comment by slafleche** [comment]
> @charrondev
> 
> > @alex-mtl when I look at the story [chromaticqa.com/snapshot?appId=5d5eba16c782b600204ba187&id=5e1cdde785e3fb0020bb023f](https://www.chromaticqa.com/snapshot?appId=5d5eba16c782b600204ba187&id=5e1cdde785e3fb0020bb023f) I only ever see 2 columns even though it looks like there are supposed to be 3 and 4 columns variants.
> 
> That is chromatic preview issue/limitation.
> 
> If you check real storybook page you will see 3 and 4 columns. According to @slafleche the layout should stay flexible and responsive. That means that visually depending of the media width it could look "2 columns" or even "1 column" but the design styles and component are rendered as 3 or 4.

Not sure what you mean @alex-mtl ... they should be responsive, but you should be able to display the previews in storybook.

**Comment by charrondev** [comment]
Looks like even with the wider viewport applied to chromatic something's not applying properly 

image

**Comment by alex-mtl** [comment]
@charrondev I don't know what is going on with chromatic. Now it shows my story as new one with no preview of the old one and preview is fine.

**Comment by charrondev** [comment]
Cool. I see them reflecting in the storybook now.

**Pull request merged**
