### PR TITLE
Fix CSRF check when deleting a ban

### PR DESCRIPTION
**Pull request by initvector**
How the "delete ban" workflow currently happens:

1. User clicks "Delete" on a record row on /settings/bans.
2. User clicks "Okay" in the popup to confirm the deletion.
3. `SettingsController::bans` checks to see if `isAuthenticatedPostback` and fails, because the request is not sent with POST, nor does it contain the session's `TransientKey`.

This update adds the transient key to the delete link by way of the `Gdn_Theme::link` function and has `SettingsController::bans` check for a valid transient key in the URL parameters before committing the deletion.

### CODE REVIEW

**Comment by linc** [comment]
We're trying to avoid passing the TransientKey during additional `GET` requests. Is it possible to remedy this via `POST`?

**Comment by initvector** [comment]
It's a little trickier, since the request goes through a confirmation popup.  If we want to keep things the way they are, but have the request made over POST, it might be necessary to edit our popup JavaScript to allow post request as part of its configuration on a link/button.

**Comment by linc** [comment]
I'm OK with some tinkering necessary; part of our ongoing security effort has been to get this out of the URL entirely, so I'm loath to take a step backwards here and add it in. That said, if it's a many-hour modification then let's table it for now and just use this.

**Comment by initvector** [comment]
No big deal.  I've updated our `jquery.popup` capabilities to allow specification of request method.  It defaults to `GET`, so everything else relying on these popups should continue to function without any updates.  If the method is `POST`, the user's transient key is added to the request data.

**Comment by Daazku** [comment]
Related: #3369

**Pull request merged**
