### PR TITLE
Update recent post when moving a discussion

### PR DESCRIPTION
**Pull request by bleistivt**
#1410 This needs to be tested with caching enabled and multiple discussions.

### CODE REVIEW

**Comment by linc** [comment]
Can you make it also fix the counters? +1 / -1

**Comment by linc** [comment]
Verified this does work with caching enabled.

**Comment by bleistivt** [comment]
This became a little more verbose. Should I resubmit against stage?

**Comment by linc** [comment]
Nah, we're avoiding stage nowadays.

**Comment by linc** [comment]
My test went like this. I checked 2 discussions from Category A and 2 from Category B and moved them to Category C.

Expected counter changes:
* A: -2
* B: -2
* C: +4

Actual change:
* A: -4
* B: 0
* C: 0

I ran /dba/counts to fix my counters. I then repeated the test with D, E, & F, moving 4 from D and 1 from E all into F.

Actual changes:
* D: +2
* E: +1
* F: +7

Caching is disabled. Something is amiss here.

**Comment by initvector** [comment]
It looks like this automatically assigns whatever discussion is being moved to be the most recent for a category, regardless of the date it was created.  If I move a discussion from an hour ago into a category with a discussion from five minutes ago, the hour-old one appears as the "Most Recent".  Running dba/counts corrects that to the five-minute-old discussion.

**Comment by bleistivt** [comment]
This would mean that CategoryModel::SetRecentPost is not working as intended:
https://github.com/vanilla/vanilla/blob/master/applications/vanilla/models/class.categorymodel.php#L1815-L1826

I can't find anything though, it sorts by DateLastComment.

**Comment by bleistivt** [comment]
@initvector I can't reproduce this. Did you do your test with caching enabled?

**Comment by linc** [comment]
I couldn't reproduce either, and if that's a bug it has nothing to do with this PR, so we're all set here. :) Thanks!

**Pull request merged**
