### PR TITLE
New variable in PluginInfo for documentation

### PR DESCRIPTION
**Pull request by slafleche**
Added links Social Connect Addons and Plugins pages to docs.
Added new variable to PluginInfo that allows you to add a link to a docs page. This variable adds an icon next to the title of the plugin.

Closes: https://github.com/vanilla/vanilla/issues/5508

### CODE REVIEW

**Comment by DaazKu** [comment]
This will conflict with https://github.com/vanilla/vanilla/pull/5542

**Comment by slafleche** [comment]
I'll refactor my PR after https://github.com/vanilla/vanilla/pull/5542

**Comment by linc** [comment]
Needs conflict resolution.

**Comment by slafleche** [comment]
New PR: https://github.com/vanilla/vanilla/pull/5614

**Pull request closed without merging**
