### PR TITLE
Verify that discussions titles render properly when no word characters are found in them.

### LINKED ISSUE #4196: Disallow Emoji being used as subject
Currently, when someone creates a discussion with a subject using an emoji (as in the kind used on mobile devices), this results in an inaccessible discussion with a blank subject line. We should either render the emoji or, perhaps simpler, just disallow these non-standard characters from being used in subjects.

### PR DESCRIPTION
**Pull request by DaazKu**
That one was a bit tricky. Emojis were introduced in the Unicode Standard 6.0.

Some system may or may not render them properly.
I decided to implement a client side solution that check if titles are rendered properly by the browser.

Fix #4196

### CODE REVIEW

**Comment by linc** [comment]
Do we even have a reproducible example of this yet?

I'm almost OK with this as a general enhancement to bulletproof our rendering, but as a primary strategy for dealing with potential garbage data I don't like it.

**Comment by DaazKu** [comment]
Yeah. Set the title field to '\x01' using javascript.
Or using an Emoji character as the title.

**Comment by linc** [comment]
Uh. I think you better make a new feature branch and cherry pick or something.

**Comment by DaazKu** [comment]
Holy #$@#.. I'm gonna do a new PR.

**Pull request closed without merging**
